### ISSUE TITLE
Activiteiten: Functie om te helpen bij wekelijkse nieuwsbrief

### ISSUE THREAD

**Issue by BorBorBor** [GEWIS/gewisweb#100]
Waarom zitten in de weekmail andere activiteiten dan op de site staan? Heel raar eigenlijk. En waarom moeten mensen hier de secretaris van GEWIS handmatig voor mailen? 

Je wil nog steeds wel dat de mails met de hand worden verstuurd zodat er ook meer info van het bestuur bij kan en zo, maar een deel van dit proces kan worden geautomatiseerd als mensen bij het activiteit-aanmaken kunnen aangeven dat hij met de nieuwsbrief mee moet en of ze dit liever in de eerstvolgende willen of in de week van de activiteit. Vervolgens kan de secretaris ergens een overzicht uit plukken van wat in de huidige week mee moet volgens de website. 

Dit scheelt de secretaris én de leden werk. Toppie!

**Comment by jszanto** [comment]
Idee: de nieuws berichten uit de nieuwsbrief als losse nieuws items op de site zetten en dan een knop op de website om de nieuwsbrief te genereren.

**Comment by gafderks** [comment]
Van de losse berichten kun je dan misschien gelijk een RSS feed maken.
