### ISSUE TITLE
Websites are not properly displayed at Jobs

### ISSUE THREAD

**Issue by Koen1999** [GEWIS/gewisweb#1011]
File to be adjusted (possibly in combination with Job model): https://github.com/GEWIS/gewisweb/blob/master/module/Company/view/company/company/jobs.phtml

Link should also be highlighted.

Refer to the mail from Max, June 25th

**Comment by Koen1999** [comment]
Apparently this feature was removed in a hotfix in 15c88beaf7db947e4151e3cc60a343ae2b487b62 .

@jszanto Was there a security issue with this feature or why did we remove it?

**Comment by jszanto** [comment]
I think it was removed because there was no check in place if the website was null. Unfortunately the commit message is not very useful, so I am not sure.

**Comment by jszanto** [comment]
I also believe this feature was actually removed per request of the board in favor of attachments for jobs.

**Comment by tomudding** [comment]
This was changed by #1019.
