### ISSUE TITLE
Photos which do no longer exist as a file but are still in the database result in an exception

### ISSUE THREAD

**Issue by tomudding** [GEWIS/gewisweb#1015]
While something like this should not happen, the exception should be caught and a 404 should be shown to the user.

**Comment by Koen1999** [comment]
I do think this is more of a server issue though. So 5xx error would be more appropriate. Ideally, we shouldn't have these database entries anymore at all.

**Comment by tomudding** [comment]
@Koen1999 This is a side effect of #583. However, I do now agree with you that the error is appropriate.

I made this issue because this is an active problem on the website. We can discuss in private where it exactly happens. But this results in photos not being downloadable in the old photo viewer and not being viewable in the new photo viewer. And in the case of the website this means that a whole album is blank.
