### ISSUE TITLE
Application Legacy service cannot always be found

### ISSUE THREAD

**Issue by tomudding** [GEWIS/gewisweb#1023]
Due to the reduced amount of errors we can once again see useful things in the logs. One of those things is this error.

> exception 'Zend\ServiceManager\Exception\ServiceNotFoundException' with message 'Zend\ServiceManager\ServiceManager::createFromInvokable: **failed retrieving "applicationservicelegacy(alias: application_service_legacy)" via invokable class "Application\Service\Legacy"; class does not exist**' in /var/www/gewisweb/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php:1069

The circumstances in which this error is created are unknown to me, but they always start here:

> /module/User/Module.php(203): Zend\ServiceManager\ServiceManager->get('application_ser...')

https://github.com/GEWIS/gewisweb/blob/dfccad80f860311560b0e94098a265f3c85b10e4/module/User/Module.php#L200-L208

The file does exist and appears to be correctly configured in the Application module.

For the full stack-trace check the logs.

**Comment by Koen1999** [comment]
The legacy service is dropped anyway.
https://github.com/GEWIS/gewisweb/pull/1119
