### ISSUE TITLE
Make new photo viewer the default photo viewer

### ISSUE THREAD

**Issue by tomudding** [GEWIS/gewisweb#1025]
After #1017 is merged, as discussed during one of our meetings, the new photo viewer should be made the default photo viewer. To prevent problems the old photo viewer will be available via a message similar to the new photo viewer currently is.

This also concludes #461.

**Comment by jszanto** [comment]
Few things TODO's left I think:

- [ ] Iron out any remaining front-end bugs
- [ ] Adjust the calculation for photo of the week so it uses the new voting system
- [ ] Make users more aware of the voting system for the photo of the week
- [ ] Figure out how the image server will be deployed in production
- [ ] Adjust links to single images to use the new photo viewer. E.g. for birthdays or photo of the week.

**Comment by tomudding** [comment]
[ ] #991 crashes the whole album instead of just a single photo.

**Comment by tomudding** [comment]
I will start working on this again soon, hence I am updating this with more information.

> @tomudding: Retain voted information when revisiting a photo (i.e. I voted for photo x but after refreshing the page it looks like I did not vote)

This is caused by the following snippet: https://github.com/GEWIS/gewisweb/blob/55864822ff15ab5d6b190b14fc02be013766e542/public/js/photo-new.js#L327-L333

The listen function from the library does not pass `item`s, hence updating the vote fails as the element is always `null`.
