### ISSUE TITLE
Add option to filter vacancies based on label

### ISSUE THREAD

**Issue by Koen1999** [GEWIS/gewisweb#1036]
This is a request from Jealy/C4

They had the idea to add a filter option in the grey search bar where you can also select the sorting, so we could possibly do this front-end.

In case a vacancy does not have any labels it is preferred to always show them. (but maybe show the ones with label first)

**Comment by tomudding** [comment]
Isn't this #1024 or at least related?

**Comment by tomudding** [comment]
> In case a vacancy does not have any labels it is preferred to always show them. (but maybe show the ones with label first)

If I may suggest something, by default show everything, then when filtering only show options that apply (thus don't show vacancies that do not have tags).

**Comment by Koen1999** [comment]
Yes, this is indeed a duplicate of #1024
