### ISSUE TITLE
Measure page views or other useful statistics for web admins and content admins

### ISSUE THREAD

**Issue by Koen1999** [GEWIS/gewisweb#1038]
This is a request from Jealy/C4, but I think that we can implement this for the whole website.
It should also be useful for us and/or the board in general.

**Comment by cebgewis** [comment]
I was wondering whether we could just implement, for example Google Analytics? I understand this would require a change in privacy statement, but that is something to consider in collaboration with the board and the GM?

Looking forward to hearing what you think about this!

**Comment by tomudding** [comment]
I am closing this issue as we have Matomo Analytics since [v2.2](https://github.com/GEWIS/gewisweb/releases/tag/v2.2).
