### ISSUE TITLE
API Request Activities list 403 forbidden

### ISSUE THREAD

**Issue by Yoronex** [GEWIS/gewisweb#1045]
Small bit of context: I am currently rewriting the TVPC script in Typescript. 

When I try to request the list of activities (GET https://gewis.nl/api/activity/list) with an API Token in the X-Auth-Token header, I get an 403 Forbidden error. This is both with a new token as well as the currently used token. The token is however valid, because I can request a photo album (GET https://gewis.nl/api/photo/album/1824) just fine. Also, it does not seem to be a firewall issue, as the request also does not work on a GEWIS computer.

**Comment by Koen1999** [comment]
Dear @Yoronex 

Currently the web server (managed by CBC) blocks your request unless it originates from localhost. This is because an authorization check is missing.
Assuming the TVPC script is run from there, there should be no issues.
We will work on tackling this issue anyway.

**Comment by Koen1999** [comment]
We have forwarded the request to the CBC.

**Comment by Koen1999** [comment]
The CBC has opened up access to the API for the TU/e IP range.
So you can now use it from the VPN for example.
