### ISSUE TITLE
Feature request: API Endpoint for random infima

### ISSUE THREAD

**Issue by Yoronex** [GEWIS/gewisweb#1047]
Currently, the tvpc (posterscherm) gets an infima by reading a file on the GEWIS server. This is absolutely disgusting and will break in the future when the CBC finishes the server migration. Therefore it would be great to have an endpoint to get a random infima from the database.

**Comment by Koen1999** [comment]
Dear @Yoronex, 

The infima are supplied by supremum. The gewis website gets the infima in the same way as you describe.
I suggest you consult Supremum for alternatives.
