### ISSUE TITLE
Feature request: watermark uploaded PDF's for education archive

### ISSUE THREAD

**Issue by Yoronex** [GEWIS/gewisweb#1049]
There has been an incident in which someone copied many documents from our education archive and published them for their own gain on websites like Studeersnel. To prevent this and to get leverage on taking these down, we need to "protect" our documents. The best and probably easiest way to do this, is to watermark every document in our archive with the GEWIS logo. At a glance anyone can see these documents are "owned" by us.

With this issue, I would like to request that all PDF's that are uploaded to the education archive get watermarked automatically. This seems to be possible within PHP with a library called FPDF. However, I am not knowledgable with PHP nor the GEWISweb repository. Existing documents can be watermark all at once manually.

**Comment by Koen1999** [comment]
I suggest that watermarks are generated when a user downloads them, and contain the IP address from which it was done.
Note that it is not an option to include the membership number since also non-members are allowed to download documents (unless this is something we would like to change?).

**Comment by rinkp** [comment]
If it is to detect who downloaded a certain file, it might also be wise to include the timestamp the file was downloaded.
As far as I know the TU/e still keeps track of who had what IP address at what time. However, this does bring a problem for the new Strongswan VPN as that one does not give all users their own external IP address.
