### ISSUE TITLE
Redirect after login does not work if first authenthication attempt is unsuccesful

### ISSUE THREAD

**Issue by Koen1999** [GEWIS/gewisweb#1050]
```
I have just found a bug on the website with respect to logging in/redirects. The bug (and reproduction) is as follows:
1.	Attempt to access a restricted resource (e.g. exam of 2INC0)
2.	Attempt to login with bogus information (e.g. username: aaa, password: aaaaaaaa)
3.	After that (rightfully) fails, log in with normal information
4.	You will be logged in but remain on the login page instead of being redirected to the requested resource. 
I have tested this on Microsoft Edge version 87.0.664.66 and Google Chrome version 87.0.4280.88. On both browsers it bugs out.

It's nothing major but it would be nice to see it fixed.
```

Credits to Daniël

**Comment by tomudding** [comment]
This currently "expected" behaviour from the implementation of https://github.com/GEWIS/gewisweb/blob/55864822ff15ab5d6b190b14fc02be013766e542/module/User/src/User/Controller/UserController.php#L38

User tries to login, but fails and is redirected to the actual login page. At this moment the `redirect` query does not exist in the URL and the `referer` (referrer) is set to the last page (the restricted page). Then, the user will login with the correct credentials. `redirect` is empty and thus ignored. However, now the `referer` is the login page, hence the user will be redirected to the login page.

An actual example:
![GEWIS-WEB #1050 Problem](https://user-images.githubusercontent.com/4983571/103283311-86e74880-49d8-11eb-9908-0040f2da16b4.png)
