### ISSUE TITLE
Mismatch between cropping aspect ratio and viewing aspect ratio for organ cover images

### ISSUE THREAD

**Issue by LeonVreling** [GEWIS/gewisweb#1052]
When adding a cover photo or profile picture for an organ, some arbitrary dimensions are used for a crop. These dimensions are not mentioned anywhere (that I could find), which makes it hard to make a fitting design to place there.

Could you maybe add these dimensions somewhere, maybe as a tooltip next to their respective upload buttons (as an idea)

**Comment by tomudding** [comment]
Hi @LeonVreling!

Thank you for your bug report. However, this should already be the default behaviour: when you select a photo to be used as a profile picture or cover a cropping tool should be displayed. Can you describe the steps you do to try to add and/or change the profile and cover pictures (without any sensitive information)?

**Comment by LeonVreling** [comment]
Hi @tomudding,

Thanks for your quick reply!

To upload the cover picture, I went to Members > Admin > Organs > GSM, and there I uploaded a picture. The uploaded picture was a Photoshop design, attached here. As you can see, there is a larger red border on the top and bottom. I added these for the cropping to definitely make it fit in the width.
![image](https://user-images.githubusercontent.com/49942406/104633803-fd09d180-569f-11eb-966c-11ae3d007b8c.png)
After the file upload, a crop tool popped up. I cropped the image, which is stored at https://gewis.nl/data/d7/7c85f25e605bf7d26729315a5805e762136046.jpg
(according to the source code of the GSM page via F12). Clearly in this picture, the borders are less than in the uploaded png from photoshop. This was done with the cropping tool.

If you look at the GSM page (https://gewis.nl/association/committee/GSM), however, there are entirely no red borders around the picture. So (my guess), an extra crop is added overtop the old crop when displaying the image, or only the centre of an image is shown.

My guess is that this is not intended behaviour, since the two cropping size are different from each other, therefore one of them can probably already be removed.

I hope this is clear enough of an explanation!

Ps, there should not be any sensitive information here, since it's all publically available on the GEWIS page or on our Instagram page

**Comment by tomudding** [comment]
Thanks for the detailed walk-through! The image is indeed successfully cropped when uploaded. However, when viewing the GSM committee page, as you indicated, the red borders are not shown. This is done to preserve the aspect-ratio of the image across all devices. It is not specific to this image, all images have this. We do use a specific aspect ratio to display the images as this is internally done by the CSS definitions.

From what I have seen the CSS displays the images with an aspect ratio of (approximately) 4:1 (with a fixed width).  If we were to change this behaviour to show the complete image, the result would similar to this:
![GEWIS-WEB #1052 Weird Cropping Non-Standard CSS](https://user-images.githubusercontent.com/4983571/104641538-2fb8c780-56aa-11eb-8fb0-9ee53f336a6a.png)

Which does not look to good. Which means something else is wrong. As you guessed it, one cropping ratio is "wrong", and it appears that the cropping tool uses 4:1.25 when uploading the image.

**Comment by Kevinjil** [comment]
We could change the [aspect-ratio SCSS mixin](https://github.com/GEWIS/gewisweb/blob/5aaece8ea3be290b19a8b95369a720dd9c938d2d/public/scss/modules/_frontpage.scss#L7) to the [aspect-ratio](https://caniuse.com/mdn-css_properties_aspect-ratio) CSS property. This property seems well supported in all modern browsers, and yields a constant aspect ratio from the testing I have performed, in contrary to the mixin which conflicts with some padding issues.

**Comment by tomudding** [comment]
The only problem is that this will "break" some of the existing images that account for the padding.

**Comment by Kevinjil** [comment]
After a quick check on the organ pages, I think showing the full image is only a problem at [GEFLITST](https://gewis.nl/nl/association/committee/GEFLITST). Perhaps we could notify them to give them some time and then apply the fix?
