### ISSUE TITLE
English vacancy page is broken

### ISSUE THREAD

**Issue by jealyvda** [GEWIS/gewisweb#1058]
The page for vacancies is broken on the English version of the website: https://gewis.nl/career/vacancies

The Dutch version still works and even the English versions of the internship, graduation page, etc are also still working. However on this page there are no more GEWIS style attributes and the company logos are all over the place..

**Comment by Koen1999** [comment]
I investigated and quite suprisingly, it looks like an error occured during the rendering of the nav-bar.
![afbeelding](https://user-images.githubusercontent.com/32361020/107150444-1845c500-695e-11eb-97ee-ccf89b39cfff.png)
