### ISSUE TITLE
Single-Sign-On for other GEWIS applications

### ISSUE THREAD

**Issue by Yoronex** [GEWIS/gewisweb#1061]
At this moment, there is no real system to allow GEWIS members to have only one login for all GEWIS systems. The one Rex and the _Openhoudscherm_ currently use are SuSOS, but that system will also soon be taken offline. In that case, everyone has to create new login credentials for the new _Openhoudscherm_, but also for a system I am currently working on: ParelPracht.

It would therefore be great if there is some sort of Single-Sign-On implemented, so members can authenticate themselves via the GEWIS website, needing only one login for all systems.
However, authorization will then be necessary, so the GEWIS website should also provide information about committees, fraternities and whether someone is in the board. In the example of ParelPracht, only C4, KCC and board members should be allowed to access the system. This authentication can be done in ParelPracht, but then ParelPracht has to know who is in what organ of GEWIS.

I am not really _in the loop_ about this, but I heard that the CBC is also requesting a feature like this, so people can use it to login to their webmail or things like that. I am not really sure about this though.

**Comment by kokx** [comment]
This is something that we had some thought about before, together with the CBC. We would be using Keycloak to manage identities within GEWIS. Nothing came of it so far, but it looks like this would be a great idea.

**Comment by christiaangoossens** [comment]
Yep, according to my conversation with @Koen1999, we have the JWT option and using the GEWIS API to pull the rest of the data (https://github.com/GEWIS/gewisweb/wiki/External-authentication), and we should be able to authenticate using nginx_auth with the site, which puts the member id, name, email and groups in headers that will be sent on your requests.

We're not sure about the long term stability of those options though, and looking into the possibilities of making some Keycloak setup with the AD for members at GEWIS. This however, will only be implemented upon the implementation of member accounts. For now, I think it's better to use one of the options above.

**Comment by tomudding** [comment]
Closing this as we have Keycloak for everything an active member can access. Everything else goes through the JWT external app adapter on the website.
