### ISSUE TITLE
Display activity correctly when not all English data is present

### ISSUE THREAD

**Issue by LeonVreling** [GEWIS/gewisweb#1086]
Hello dear web committee,

The past week or so, the GEWIS link in bio page has been displaying a "null" as activity name for the upcoming lunch lecture. I saw that this issue did not only occur on the API we use, but also on the GEWIS website itself (see attachment). It is kind of weird that this happens also if you display the page in Dutch, since I'm assuming the name is set for the Dutch language.
![image](https://user-images.githubusercontent.com/49942406/116244230-08bd6780-a768-11eb-86bb-199150d2dbe5.png)

Could it be the case that this happens since all information is only given in Dutch, since that is the thing for the GSM page?

-Leon

**Comment by LeonVreling** [comment]
UPDATE: I edited the GSM page to use the Dutch name when the English one is not set, and now it does display the proper name. It still leaves me curious why the actual GEWIS page does not display the activity name, in both language settings for the site

**Comment by tomudding** [comment]
By default we only show the English title on the homepage, because more often than not the Dutch translation of an activity does not exist.

As this will not be an issue with the activity overhaul (if one translation is missing the other one will be used) I am closing this issue.
