### ISSUE TITLE
Laminas Form v3 Upgrade

### ISSUE THREAD

**Issue by Koen1999** [GEWIS/gewisweb#1150]
There is a new update available for this package that will require us to make some changes. Most notable, we need to remove the DateTime fields and replace them by something else.

https://docs.laminas.dev/laminas-form/v3/migration/v2-to-v3/

**Comment by Koen1999** [comment]
Also note that an upgrade of Laminas Code depends on this. After we do this, we can upgrade to Laminas Code v4. I don't think a migration doc has been written for this yet.

**Comment by tomudding** [comment]
`doctrine/doctrine-module` requires `^v2.11` and we can therefore not update to `v3.0` until that dependency is resolved. This is also the reason I did not update `laminas/laminas-form` during the PHP 8.0 upgrade.

Seeing the slow development cycle for `doctrine-module` this may take quite some time.

**Comment by tomudding** [comment]
> (...) Most notable, we need to remove the DateTime fields (...)

This ties in perfectly with #1235. We still need to wait on `doctrine/doctrine-module`, but I have some good news in that department, this specific issue (and thus `v4.2.0`) is in the release pipeline!
