### ISSUE TITLE
Become member button

### ISSUE THREAD

**Issue by Gijsdeman** [GEWIS/gewisweb#1209]
Recently, we have received a lot of questions about how you can become a member. Of course, [join.gewis.nl](https://join.gewis.nl/) exists, but there is no way to know about this website without knowing the link. This way, a lot of new students end up on the [registration page](https://gewis.nl/user/register), which just leaves them confused.

I (read, the 40th board), think it would be a great addition to the website of in the navigation bar, a "Become member" button is added that redirects to the right page. This way, it should be clear on the homepage where you should go if you want to become a member of GEWIS.

The only issues this would give the board is to check whether new registrations are now part of the M&CS department, but this is something we can check quite easily and we already do on a daily basis.

Something like this would be fine:
![image](https://user-images.githubusercontent.com/43375368/131816615-4eef3aaf-6950-40c3-813d-4500ab22eee0.png)

**Comment by Koen1999** [comment]
This is a good idea and I think a valuable addition for the beginning of the academic year. I would opt for removing this button after the 1st of December or so. But that's something for later consideration. I'll see to it that the button is implemented.

**Comment by Koen1999** [comment]
@Gijsdeman I have one additional request though. join.gewis.nl does not highlight any of the benefits of becoming a GEWIS member. I propose you create a page on the website that describes these. This page can then link to join.gewis.nl and we can have the button in the navbar link to the new page (e.g. gewis.nl/become-member). Please let me know what you think.

**Comment by Gijsdeman** [comment]
@Koen1999 sounds like a great idea, I will see to that such a page is created. It will most likely be a page that will just fall under /association. Thanks for the great suggestion!

**Comment by tomudding** [comment]
I am closing this issue, as the changes have been merged and deployed some time ago.
