### ISSUE TITLE
Small CSS issues

### ISSUE THREAD

**Issue by Gijsdeman** [GEWIS/gewisweb#1210]
Ever since the website was transferred to the new server (and higher PHP version, I suppose), I noticed a few small stylish issues, mostly related to spacing. I know this is really low priority right now, as there are bigger issues that need to be fixed!

They are small issues as these, where first a faded spacer was added to add more space between "Studievereniging GEWIS" and the image above. This is also something I have noticed on other pages.
![image](https://user-images.githubusercontent.com/43375368/131816960-3d7043a6-888f-4c01-bdd8-ab05ca4655dc.png)

Also small spacing issues in buttons, where favicons are now directly next to the text instead of there being a small space between the, which to my knowledge used to be there before.
![image](https://user-images.githubusercontent.com/43375368/131817140-48ec9d40-37c5-4670-b1ec-4d31f555b1f2.png)

**Comment by Koen1999** [comment]
I personally don't feel like this is an issue.
