### ISSUE TITLE
Change admin view to have a sidebar instead of top navbar

### ISSUE THREAD

**Issue by tomudding** [GEWIS/gewisweb#1219]
To utilise some more space on the admin pages, I propose we change the current navbar to be a sidebar.

**Before:**
![GEWIS-WEB - Admin Pages - Overview Before](https://user-images.githubusercontent.com/4983571/132252207-ab9e41fd-5f61-4c24-8be8-0507ad6df813.png)

**After:**
![GEWIS-WEB - Admin Pages - Overview After](https://user-images.githubusercontent.com/4983571/132252805-26544894-5897-469f-b059-f99b040b5554.png)

**Comment by Koen1999** [comment]
Looks neat, but I also smell work :p
