### ISSUE TITLE
Add organ history for members

### ISSUE THREAD

**Issue by tomudding** [GEWIS/gewisweb#1222]
Samuel requested this and I think it will be a nice addition to the member pages.

**Comment by LeonVreling** [comment]
What does this feature exaclty entail, is it displaying all search results for someone's name on the decision list on their profile or something more elaborate?

**Comment by tomudding** [comment]
> What does this feature exactly entail, is it displaying all search results for someone's name on the decision list on their profile or something more elaborate?

Currently, only active organ memberships are shown on the profile page. The idea with this change is that also past organ memberships are shown.

For example, for you profile it would mean that it would show (under a new heading or something) that you were previously a member of FYC19-0 Beercode. It can even be extended to say that you were the secretary of that organ.
