### ISSUE TITLE
Photo viewer not redirecting as expected

### ISSUE THREAD

**Issue by LeonVreling** [GEWIS/gewisweb#1225]
I was just looking at the photo viewer on the website, and saw that some navigation between pictures is not as I expected it to be. You can click anywhere on the picture to go to the next picture in the series, so not only on the right arrow. This also means that if you are clicking on the left arrow to go back in the album, at some point you will get into a loop. This is the case as there is no left arrow on the first image, so then you click somewhere on the image, which means the next photo in the album.

I hope it is a bit clear what I mean, otherwise you can contact me!

**Comment by tomudding** [comment]
I would not necessarily call this a problem, but I understand why it can be annoying. As this is only an issue in the old photo viewer and we still have the intention to remove the old photo viewer (soon™), we will not fix this issue.
