### ISSUE TITLE
Add way to view poll options before approval

### ISSUE THREAD

**Issue by LeonVreling** [GEWIS/gewisweb#1231]
Currently, admins can only view the questions of a poll on the GEWIS website and not the possible things to vote on. It would be nice if this could be added so that you know the options before approving a poll.

**Comment by LeonVreling** [comment]
UPDATE: Apparently this is already a thing. You can view the poll options when you press "approve". I'd suggest changing this button to "details" to make it coherent with the workflow of approving activities.

**Comment by tomudding** [comment]
I think the current workflow works fine, so we will keep it this way.
