### ISSUE TITLE
Move away from jQuery DateTimePicker and use native input interfaces

### ISSUE THREAD

**Issue by tomudding** [GEWIS/gewisweb#1235]
With the release of Firefox 93, `datetime-local` now also has a UI in Firefox (already present in other major browsers). This means we can remove our dependency on jQuery's DateTimePicker and use the native implementations of browsers. `Laminas\Form` already has support for this specific type.

I do recommend we do wait some time before actually doing this, as FF93 still needs to be adopted.

**Comment by Koen1999** [comment]
Do you know if this only applies to desktop browsers or also to mobile?

**Comment by tomudding** [comment]
> 
> 
> Do you know if this only applies to desktop browsers or also to mobile?

Both platforms support it, mobile even a bit earlier than desktop (FF). However, like I mentioned, I would wait with actually changing this now. Somewhere later this year is perfectly acceptable in my opinion.
