### ISSUE TITLE
Photo: restructure controllers, mappers and services

### ISSUE THREAD

**Issue by jszanto** [GEWIS/gewisweb#127]
Some controller/mapper/service functions probably should be move to other controllers/mappers/services. E.g. some album related function in the photo service should be moved to the album service.

**Comment by stefanmajoor** [comment]
Do you have a list of specific controllers/mappers/services functions that need to be moved?

**Comment by jszanto** [comment]
No, the specific functions still need to be figured out. I just noticed that the way they are structured now is a bit counter-intuitive at some places. It might even be better to rename/consolidate/split up some controllers/mappers/services. However all of this is not very important, it just makes understanding the code easier in my opinion.

**Comment by jszanto** [comment]
Fixed by PR #159
