### ISSUE TITLE
Option calendar calendar not working in Chromium-based browsers

### ISSUE THREAD

**Issue by tomudding** [GEWIS/gewisweb#1339]
As reported by Leon, the calendar for the option calendar does not work in Chromium-based browsers (Chrome/Edge). The following error is reported:

> calendar.min.js:2 Uncaught TypeError: this.options.templates[this.options.view] is not a function
>     at j._render (calendar.min.js:2:7912)
>     at j.view (calendar.min.js:2:13307)
>     at new j (calendar.min.js:2:2932)
>     at n.fn.init.a.fn.calendar (calendar.min.js:2:22353)
>     at initCalendar ((index):4839:35)
>     at Object.success ((index):4822:9)
>     at i (jquery.min.js:2:27449)
>     at Object.fireWith [as resolveWith] (jquery.min.js:2:28213)
>     at y (jquery.min.js:4:22725)
>     at XMLHttpRequest.c (jquery.min.js:4:26929)

**Comment by tomudding** [comment]
It appears that something has changed in `XMLHttpRequest` which prevents the calendar from loading the template files:

> Error - 0: NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://gewis.nl/tmpls/month.html?_=1643393136505'.

**Comment by Koen1999** [comment]
Firefox hinted the following:
`Synchrone XMLHttpRequest op de hoofdthread wordt niet meer ondersteund vanwege de nadelige effecten op de eindgebruikerservaring. Zie http://xhr.spec.whatwg.org/ voor meer informatie jquery.min.js:4:26278`

**Comment by tomudding** [comment]
> Firefox hinted the following: http://xhr.spec.whatwg.org/ `Synchrone XMLHttpRequest op de hoofdthread wordt niet meer ondersteund vanwege de nadelige effecten op de eindgebruikerservaring. Zie http://xhr.spec.whatwg.org/ voor meer informatie jquery.min.js:4:26278`

Yes, I was just about to say that the `$.ajax()` requests (which is `XMLHttpRequest` in a jquery layer) has its flags set to `async: false` in the calendar library. However, manually setting these to `true` does not resolve the issue, as the template is not loaded before it has to be used.

It appears that Chrome has finally removed synchronous `XMLHttpRequests` somewhere in November/December of 2021.

**Comment by tomudding** [comment]
The issue is shown in this image. The `templates` dictionary is empty before the error occurs. The contents of the `month` key are loaded after the error has already occurred.

It is probably easier to switch to an alternative calendar, as this calendar has not received any recent updates.

![image](https://user-images.githubusercontent.com/4983571/151601514-1db3bf87-e822-4001-b5f7-9219f8f30491.png)
