### ISSUE TITLE
Move away from Google Fonts due to GDPR

### ISSUE THREAD

**Issue by tomudding** [GEWIS/gewisweb#1346]
Based on German court rulings, we may have to move away from using Google Fonts. While we can download Raleway and host it ourselves, it might be a good time to switch away from the custom font and just use whatever is available on the user's operating system.

Would also help us prepare for switching to bootstrap 5 later this year (but Tom, I didn't know we would do this? Correct, but I will be doing it during the summer).

**Comment by Koen1999** [comment]
Moving towards bootstrap 5 would be a great step! Definitely a good idea after we finished the company module overhaul.

**Comment by tomudding** [comment]
Regarding the GDPR violation, I have sent Rink an e-mail to hopefully get a better understanding on how quickly we should remove the fonts (i.e. temporarily switch to locally hosted).

**Comment by Koen1999** [comment]
Based on my knowledge of how GDPR works, we should either ask for consent to use Google Fonts for each user (not practically feasible), or we should base our usage on legitimate interest. But the latter also requires us to provide an opt-out (like we did with Matomo), but that's also not practical.

I suggest moving to locally hosted fonts or system native fonts. In fact, the latter is preferred.

But in all honesty, given the extent and impact of this violation; the priority required to tackle this is not that high. We should definitely take action, but we can take our time to determine the best course of action first.

**Comment by Koen1999** [comment]
Another issue relating to this is that we also serve content from other websites like YouTube or Vimeo. The same reasoning applies to these so we should make sure we have a larger plan to also account for these.

**Comment by tomudding** [comment]
> Another issue relating to this is that we also serve content from other websites like YouTube or Vimeo. The same reasoning applies to these so we should make sure we have a larger plan to also account for these.

Yeah, perhaps we should make that part of the company module overhaul. I know that with CKEditor 5 it is easy to just provide some dummy DOM which can be easily translated into the actual iframes when accepted by the user (through some simple JavaScript). I don't know how easy it will be with the current CKEditor (4), since upgrading to 5 is not yet possible (GHS is not good enough yet).
