### ISSUE TITLE
Birthdays are no longer shown on frontpage

### ISSUE THREAD

**Issue by rinkp** [GEWIS/gewisweb#1349]
I am not sure whether this is intentional, but I wasn't able to find a commit or issue that explicitly referenced this

**Comment by Koen1999** [comment]
Is it a possibility that there are no birthdays today?

**Comment by tomudding** [comment]
No, I checked and there are >10 birthdays today. This started happening when we deployed the latest version, which includes this commit: 34524ce10280cdd773d290ab9e83304a202fd87c.

In that commit the logic was changed, the query now selects birthdays that are exactly today (of which there are obviously none).

I want to fix multiple bugs tonight, so I'll fix this too and deploy a new version for tomorrow.

**Comment by tomudding** [comment]
I will also (try to) rewrite the query to be understandable instead of the old one which can be a bit difficult to understand (but was limited by missing functionality in the db driver, which should not be a problem today).

**Comment by Koen1999** [comment]
Oww woops. Yeah, I had to change that query because the syntax wasn't supported by Sqlite. But apparently I did a bad job.

**Comment by tomudding** [comment]
> Oww woops. Yeah, I had to change that query because the syntax wasn't supported by Sqlite. But apparently I did a bad job.

I have taken a look at it, and there isn't really a way that supports SQLite. All date and time functions are completely different from MariaDB.

On top of that, the current (old) implementation handles overflows on its own, adding custom functions to handle that makes this way too complicated.
