### ISSUE TITLE
PHPUnit action very slow

### ISSUE THREAD

**Issue by tomudding** [GEWIS/gewisweb#1366]
Since #1362 the action for PHPUnit has become terribly slow. From approximately 1 minute per run it now averages around 9 minutes. I don't see why it would suddenly be slow, but it is.

@Koen1999 Any idea?

**Comment by Koen1999** [comment]
The test that is taking so long is the AutomaticController test.
I'm not sure why it has suddenly become so slow. It's either an update to PhpUnit or one of the laminas packages.

**Comment by tomudding** [comment]
It is still a bit slow, but is now 1-2 minutes per run. I think that is acceptable but we must keep an eye on it and if it happens again we should try to contact GitHub to see why it is slow.
