### ISSUE TITLE
Language defined in layout.phtml in insensitive to translator locale

### ISSUE THREAD

**Issue by Koen1999** [GEWIS/gewisweb#1367]
https://github.com/GEWIS/gewisweb/blob/2066bfa74a0188a2060e93114fa247ebca234ac2/module/Application/view/layout/layout.phtml#L3

This tag should vary depending on the locale set in the translator.

Moreover, we should also consider adding http-equiv meta tags for the other languages. But for this, we should implement some sort of referral mechanism for switching languages that does not just redirect to the homepage.

Please see: https://www.seobility.net/en/wiki/Declaring_language_in_HTML

**Comment by tomudding** [comment]
Perhaps we should also consider setting the default language to English. I wonder why this was never mentioned during the CMs last year, as inclusiveness for non-Dutch speaking people was a major point.

Looking at the other study associations, only Protagoras has their default language set to Dutch too, all the other study associations default to English.

**Comment by Koen1999** [comment]
Good point. We can change the default.
Perhaps to accommodate the Dutch, we can implement a default switch of language when logging in.

**Comment by tomudding** [comment]
We should probably also store the user's preference in `Window.localStorage`, that way it won't suddenly switch when the real session expires (not the JWT session).

Unrelated, but if we eventually make the rainbow navbar accessible to normal members and/or implement a dark theme (with Bootstrap 5/6), we can change the current language dropdown to be a settings menu.
