### ISSUE TITLE
Inefficient requests for infimum on Frontpage

### ISSUE THREAD

**Issue by Koen1999** [GEWIS/gewisweb#1372]
On https://gewis.nl/ , when logged in, two requests are sent to retrieve the same infimum.
This obviously is inefficient. We should refactor the code somehow to make this one request even though the text is displayed in the spots on this page.

**Comment by tomudding** [comment]
It could definitely be done with one request; put it in the `<head>` (if you want it early, if it does not matter, just keep it at the bottom and make wait till the DOM has finished loading) where it sets a variable and then use that variable in both places.

However, seeing that the responses take less than 30ms to arrive (when the infimum was cached) that one extra request does not seem particularly inefficient (especially with HTTP/2).

**Comment by Koen1999** [comment]
It's only cached at the server, not at the client. Therefore clients with slow internet connection will probably notice.
