### ISSUE TITLE
bug/feature for Tagging members in Pictures

### ISSUE THREAD

**Issue by JustSamuel** [GEWIS/gewisweb#1374]
With the beta viewer tagging has become more tiresome again. If possible could (some) of the following suggestions maybe be implemented?

- If there is only a single suggestion it should be auto togged OR if you type a full name it should be auto tagged
- If you have just tagged someone, or have the tag some text box selected it should be auto focused when switching image.

<3

**Comment by Koen1999** [comment]
Just as a sidenote, you can select the correct user with your keyboard arrow buttons once a few options have appeared.

**Comment by Koen1999** [comment]
The first suggestion is not something that we can make happen because the autocompletion is an external library.

**Comment by JustSamuel** [comment]
Not even that if there is a single match pressing enter will tag?

**Comment by JustSamuel** [comment]
Also. you are unable to tag people starting with a Z

**Comment by tomudding** [comment]
I don't know why the auto tagging does no longer work, we haven't really touched that part of the code. But I'll look into it.

> Also. you are unable to tag people starting with a Z

Can you privately share the name of the member(s) with me? I do not have any issues tagging members whose name start with a "Z".

**Comment by tomudding** [comment]
> Can you privately share the name of the member(s) with me? I do not have any issues tagging members whose name start with a "Z".

It is "z" and not "Z". Is used for zooming the photo viewer. New behaviour will disable zooming when the tag search box is in focus.
