### ISSUE TITLE
Change ordering activity archive to descending by year

### ISSUE THREAD

**Issue by LeonVreling** [GEWIS/gewisweb#1378]
Currently, the photo archive is ordered with the most recent on the left, and the activity archive is ordered the other way. Preferably, this would go both in the same order for user-friendliness

**Comment by tomudding** [comment]
I think the ordering as seen on the Photos page is preferred. A lot easier to read it LTR in decreasing order.

**Comment by LeonVreling** [comment]
As a second part, maybe we also want to reverse the order of activities on the archive page itself, since now the summer drinks are always at the beginning, and the most recent activity is always at the bottom
