### ISSUE TITLE
`Set as profile picture!` is shown on pictures you are not tagged in

### ISSUE THREAD

**Issue by rinkp** [GEWIS/gewisweb#1396]
The new photo viewer shows the "Set as profile picture!" button always, even when not showing your own photos

**Comment by tomudding** [comment]
Known issue :(, but we do not have a better solution at this point in time, as we do not auto-dyna-magically update the tags.

I will do something in #1391 which will reintroduce the am-i-tagged status on a per photo basis once (when the tags are loaded), but I do not have a good solution for when you add/remove a tag for yourself (as I do not think we can update the PhotoSwipe UI for a loaded slide).
