### ISSUE TITLE
It is possible for a member to receive more than 2 authorizations

### ISSUE THREAD

**Issue by rinkp** [GEWIS/gewisweb#1399]
It is possible for a single member to receive more than 2 authorizations, while according to the bylaws this should be at most 2. Moreover, all authorizations are marked as valid in the frontend

**Comment by tomudding** [comment]
I have taken a closer look and in the eternal memorandum it is stated that this is not a problem. The person receiving the authorizations has to decide which of the authorizations (not more than 2) they will use.
