### ISSUE TITLE
Request for more user details in JWT token 

### ISSUE THREAD

**Issue by JustSamuel** [GEWIS/gewisweb#1403]
Dear Web,

As you might know we are working very hard on SudoSOS. We are at the time in development where we are trying to merge it into the current GEWIS ecosystem. One of the main use cases is inactive members who only have a Web account logging into SudoSOS.

SuSOS solves this problem by direct connection to the DB, we would prefer to do it in a nicer way. Would it be possible to get more information from the WEB JWT token to be able to create an account? We only need membership number, first- last name and an e-mail to so.

If you disagree with anything, let me know, I could always use your input.

**Comment by rinkp** [comment]
+membership status (not everybody on the website is a member of GEWIS)

**Comment by tomudding** [comment]
This should not be a problem but I'd like to point out that this will only be the case for our [external authentication JWT tokens](https://github.com/GEWIS/gewisweb/wiki/External-authentication) (and not the cookie token).

**Comment by tomudding** [comment]
@JustSamuel We still want to discuss something with @rinkp regarding this change, but you can prepare SudoSOS to receive the following claims in the token:

- `given_name`      => given name or first name
- `family_name`     => given surname or last name
- `email`           => email address
- `membership_type` => type of membership

`lidnr` already existed.

Regarding the membership type, your best reference for the actual values will be [gewisdb](https://github.com/GEWIS/gewisdb/blob/6e7ca59e3fd6292a9c4e7a09b103e34a2e9ef4dd/module/Database/src/Database/Model/Member.php#L20-L24). However, you should note that these will change before July 1, 2022. We will make sure that we notify you/the workgroup of the changes when they happen.

**Comment by tomudding** [comment]
Should also include an `is_18+` (or a more suitable name).
