### ISSUE TITLE
Album index.php causes error with FileUrl helper

### ISSUE THREAD

**Issue by Koen1999** [GEWIS/gewisweb#1404]
```[2022-04-06T14:58:27.313296+02:00] gewisweb.ERROR: TypeError: Application\View\Helper\FileUrl::__invoke(): Argument #1 ($path) must be of type string, null given, called in /code/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php on line 407 and defined in /code/module/Application/src/View/Helper/FileUrl.php:24 Stack trace: #0 /code/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(407): Application\View\Helper\FileUrl->__invoke(NULL) #1 /code/module/Photo/view/photo/album/index.phtml(112): Laminas\View\Renderer\PhpRenderer->__call('fileUrl', Array) #2 /code/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(519): include('/code/module/Ph...') #3 /code/vendor/laminas/laminas-view/src/View.php(194): Laminas\View\Renderer\PhpRenderer->render(NULL) #4 /code/vendor/laminas/laminas-view/src/View.php(222): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel)) #5 /code/vendor/laminas/laminas-view/src/View.php(187): Laminas\View\View->renderChildren(Object(Laminas\View\Model\ViewModel)) #6 /code/vendor/laminas/laminas-mvc/src/View/Http/DefaultRenderingStrategy.php(98): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel)) #7 /code/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Laminas\Mvc\MvcEvent)) #8 /code/vendor/laminas/laminas-eventmanager/src/EventManager.php(171): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent)) #9 /code/vendor/laminas/laminas-mvc/src/Application.php(360): Laminas\EventManager\EventManager->triggerEvent(Object(Laminas\Mvc\MvcEvent)) #10 /code/vendor/laminas/laminas-mvc/src/Application.php(341): Laminas\Mvc\Application->completeRequest(Object(Laminas\Mvc\MvcEvent)) #11 /code/public/index.php(23): Laminas\Mvc\Application->run() #12 {main} [] []```

**Comment by tomudding** [comment]
Same issue as #1381 except for sub albums, which I didn't check when I fixed that.

**Comment by tomudding** [comment]
After fixing the issue I will also generate the covers for these albums.
