### ISSUE TITLE
ApiApp service calls function on null

### ISSUE THREAD

**Issue by Koen1999** [GEWIS/gewisweb#1405]
```[2022-04-06T11:58:10.002738+02:00] gewisweb.ERROR: Error: Call to a member function getCallback() on null in /code/module/User/src/Service/ApiApp.php:48 Stack trace: #0 /code/module/User/src/Controller/ApiAuthenticationController.php(50): User\Service\ApiApp->callbackWithToken('REDACTED', Object(User\Model\User)) #1 /code/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(71): User\Controller\ApiAuthenticationController->tokenAction() #2 /code/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\Controller\AbstractActionController->onDispatch(Object(Laminas\Mvc\MvcEvent)) #3 /code/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure)) #4 /code/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(97): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent)) #5 /code/vendor/laminas/laminas-mvc/src/DispatchListener.php(132): Laminas\Mvc\Controller\AbstractController->dispatch(Object(Laminas\Http\PhpEnvironment\Request), Object(Laminas\Http\PhpEnvironment\Response)) #6 /code/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\DispatchListener->onDispatch(Object(Laminas\Mvc\MvcEvent)) #7 /code/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure)) #8 /code/vendor/laminas/laminas-mvc/src/Application.php(325): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent)) #9 /code/public/index.php(23): Laminas\Mvc\Application->run() #10 {main} [] []```

**Comment by tomudding** [comment]
Yes I was testing the endpoint, there isn't a `null` check on the the lookup:

https://github.com/GEWIS/gewisweb/blob/b6ea6c5068aaf3782e42efe81500e8408787d062/module/User/src/Service/ApiApp.php#L38-L48
