### ISSUE TITLE
Restrict access to photos for `graduate` members

### ISSUE THREAD

**Issue by tomudding** [GEWIS/gewisweb#1427]
With the upcoming (already existing) membership types, `graduate` members may only have access to photos up to the end of their membership (`ordinary`).

**Comment by Koen1999** [comment]
I think we need to consider whether this is desirable and to what extent.
For sure we cannot limit access for all graduates to all photos.
e.g., if a graduate is tagged in a photo or perhaps even tagged in a photo of an album, they should have access to that photo or album.
Alternatively, we could give them access to photos captured during their study time.

**Comment by tomudding** [comment]
> Alternatively, we could give them access to photos captured during their study time.

This is the plan of the board. However, thanks to your comment I see some additional issues that I will have to discuss with the board. For example, a `graduate` can still partake in an activity, but what happens if they are photographed during that activity?

The initial solution Rink and I came up with was simply not allowing access to albums that were created after the member's membership changed (from `ordinary` or `external` to `graduate`), as photos almost never appear alone on the website. However, if we really want to be strict we'd have to add a check for all photos, which like you mentioned will become very cumbersome.
