### ISSUE TITLE
Upgrading to Docker Compose v2

### ISSUE THREAD

**Issue by tomudding** [GEWIS/gewisweb#1460]
Somewhere later this year, Docker Compose v1 (which we currently use) will reach its end of life.

**Comment by Koen1999** [comment]
For more information: https://www.docker.com/blog/announcing-compose-v2-general-availability/

**Comment by tomudding** [comment]
Portainer 2.14 (which will be released somewhere at the end of this month) should include support for v2. I will keep in contact with the CBC to determine the upgrade timeline.
