### ISSUE TITLE
Remove `jszanto/gewisweb-test-data` as a dependency

### ISSUE THREAD

**Issue by Koen1999** [GEWIS/gewisweb#1463]
We should drop the dependency on `fzaninotto/faker` since it's long outdated.

This means we should either drop the dependency on `jszanto/gewisweb-test-data` or update it accordingly.

I propose dropping.

**Comment by Koen1999** [comment]
> Or we directly implement the generators into `gewisweb` instead of a separate repository and module. `fakerphp/faker` is the replacement for the no longer maintained `fzaninotto/faker`.

I think it is a good approach to incorporate it into the unit tests. That way we are also forced to fix any test data generators when we make database model changes.

If it's a separate repo, we will probably have difficulties with having to create two PRs and updating test data package versions all the time.

**Comment by tomudding** [comment]
I will remove `jszanto/gewisweb-test-data` as a dependency, as it has not worked for quite some time and as we know includes some outdated dependencies.
