### ISSUE TITLE
Navigation menu shows Board 2015/2016 instead of Board

### ISSUE THREAD

**Issue by rinkp** [GEWIS/gewisweb#1470]
How did this happen:
https://github.com/GEWIS/gewisweb/blame/master/module/Application/view/partial/main-nav.phtml#L139

```php
<a href="<?= $this->url('home/page', ['category' => 'vereniging', 'sub_category' => 'bestuur']) ?>"><?= $this->translate('Board 2015/2016') ?></a>
```

+bonus: menu no longer translates

**Comment by rinkp** [comment]
![afbeelding](https://user-images.githubusercontent.com/17340320/173395884-df2dc980-6368-4eeb-a188-a2b1771c0070.png)

**Comment by tomudding** [comment]
This is due to the changes in how we instantiate the translator service for the website. Apparently it no longer uses the translations defined in the PO file for English but uses the source text. Why we never updated the source text in the first place, I do not know.
