### ISSUE TITLE
`michelf/php-markdown` deprecation notice on internal method

### ISSUE THREAD

**Issue by tomudding** [GEWIS/gewisweb#1482]
Not an issue for us, but just adding it here to keep track of it.

> Deprecated: preg_replace(): Passing null to parameter &num;3 ($subject) of type array|string is deprecated in /code/vendor/michelf/php-markdown/Michelf/Markdown.php on line 233

**Comment by Koen1999** [comment]
Perhaps we can pass this down to MaglMarkdown or the mentioned dependency

**Comment by tomudding** [comment]
> Perhaps we can pass this down to MaglMarkdown or the mentioned dependency

There is a pull request open for it in the dependency, but the package does not appear to have had any activity since November last year. I am sure it will resolve itself at some point (before the PHP foundation decides to make this an actual error), but it is something we can keep an eye on.

**Comment by tomudding** [comment]
The dependency has seen some action since June, however, this problem is still not resolved (PR is still open).

**Comment by tomudding** [comment]
Due to the lack of updates to `MaglMarkdown` (and I do not want to create a pull request), I will create `gewisweb-markdown` which essentially forks the original. It should require minimal maintenance.
