### ISSUE TITLE
Issues retrieving photos from certain albums

### ISSUE THREAD

**Issue by dvanleijenhorst** [GEWIS/gewisweb#1492]
### Current behaviour

The photos between (and including) the GELIMBO carnavalscantus and the GELIMBO dieszitting are currently broken and return 500s for (almost) every photo in the album, making the albums completely unviewable. 

### Desired behaviour

Being able to view the photo's and not see the generic 'photo not found' error graphic

### Steps to reproduce

Navigate to the Photos tab
Navigate to any of the following albums:

- GELIMBO Dieszitting
- ADC Borrel
- AC x Ordina Poker Night
- FYC Battle
- BAC raketjer borrel
- GELIMBO Carnaval Cantus

and watch the error 500s roll in as no photos appear4

### Website version

v2.8.2

### What operating are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Microsoft Edge

### Other information

This also breaks the current Photo of the Week, as it features a photo from the GELIMBO Carnaval Cantus.

Not every photo in the albums are affected, notably the later photos of the dieszitting and some of the middle photo's of the carnaval cantus are still fine

**Comment by tomudding** [comment]
Thank you for reporting this! We are aware of this issue, however, er cannot solve it. The files are no longer on the server and we do not know what caused it (nor does the CBC). It also happened with the lustrum photos, which were uploaded yesterday. I will ask the board to upload the albums again.

**Comment by tomudding** [comment]
Albums have been restored by the board.
