### ISSUE TITLE
Albums with only subsubalbums don't have cover pictures

### ISSUE THREAD

**Issue by rinkp** [GEWIS/gewisweb#1503]
### Current behaviour

https://github.com/GEWIS/gewisweb/blob/80b304fbc1cdc6179b594d14a920e0fea2d4260f/module/Photo/src/Service/AlbumCover.php#L99

We only check direct subalbums, not recursively for subalbums until we have found photos

### Desired behaviour

Generating a cover for an album should have a cover photo with pictures from the topmost subalbum

### Steps to reproduce

Have an album with 0 photos, containing only subalbums with 0 photos having subsubalbums with more than 0 photos. 
Generating an album preview results in an empty picture

### Website version

cf7b469

**Comment by tomudding** [comment]
#577

**Comment by tomudding** [comment]
> Generating a cover for an album should have a cover photo with pictures from the topmost subalbum

I actually think it would be pretty nice if it could randomly select from multiple subalbums, so that you are actually showing that multiple subalbums exist (when applicable). Perhaps a native recursive SQL query would work, but that is something to figure out,

**Comment by tomudding** [comment]
#611

**Comment by tomudding** [comment]
I have written a recursive query that will enable us to do this nicely (if you do not account for the performance impact).
