### ISSUE TITLE
Upgrade `doctrine/orm` to `v2.14.0` (or `v2.13.5`) and remove patch

### ISSUE THREAD

**Issue by tomudding** [GEWIS/gewisweb#1545]
`v2.13.5` and subsequently `v2.14.0` were released for `doctrine/orm` last night. We should upgrade to this version as soon as possible to make sure that we can remove [our second patch](https://github.com/doctrine/orm/commit/3db76eb8116c4b5d1f7da4f15cf1a379fe1af333) for ORM.

**Comment by Koen1999** [comment]
Did they fix it?
:0

**Comment by tomudding** [comment]
> Did they fix it? :0

Unfortunately not the old patch. This is related to their sloppy/incomplete support for enums (and slow release of important fixes). They changed a bit of the association mappings that caused it to break when an `id` attribute had a `enumType`.
