### ISSUE TITLE
Restrict availability of session cookies on subdomains

### ISSUE THREAD

**Issue by tomudding** [GEWIS/gewisweb#1556]
Both `GEWISSESSID` and `GEWISSESSTOKEN` are currently availability on subdomains, this is not necessary.

**Comment by tomudding** [comment]
Reported by @rinkp.

**Comment by tomudding** [comment]
Requires removal of the specific domain, to prevent browsers from creating a wildcard.

**Comment by rinkp** [comment]
Maybe we can combine this with a rollover of the key because then we guarantee all cookies to be set again in any case. (since a few weeks, wiki.gewis.nl is now also abiding by this standard with the similarly named `GEWIKISESSTOKEN` (XSRF token was already hostonly)

**Comment by tomudding** [comment]
> Maybe we can combine this with a rollover of the key because then we guarantee all cookies to be set again in any case. (since a few weeks, wiki.gewis.nl is now also abiding by this standard with the similarly named `GEWIKISESSTOKEN` (XSRF token was already hostonly)

Yes that is a good idea!
