### ISSUE TITLE
Remove `*.gewis.nl` from `img-src` CSP directive

### ISSUE THREAD

**Issue by tomudding** [GEWIS/gewisweb#1558]

**Comment by rinkp** [comment]
Sounds like a reasonable thing to do. Do you know whether the connecr-src for supremum.gewis.nl is still used now infimum are cached?

**Comment by tomudding** [comment]
> Sounds like a reasonable thing to do. Do you know whether the connecr-src for supremum.gewis.nl is still used now infimum are cached?

No, it seems I have been a bit sloppy with updating it. This and the `https://fonts.googleapis.com` like you mentioned will be removed.
