### ISSUE TITLE
Font preloading issue

### ISSUE THREAD

**Issue by rinkp** [GEWIS/gewisweb#1560]
### Current behaviour

1. https://gewis.nl/fonts/lato/lato-v22-latin-italic.woff2 is not preloaded, because the font is not referenced for preload
2. https://gewis.nl/fonts/gewisicons/gewisicons.ttf?37l19n is not preloaded, most likely because of the additional = in https://github.com/GEWIS/gewisweb/blob/34e1aae4f23d63d4ba65a0ab61994059acac0558/module/Application/view/layout/layout.phtml#L58

### Steps to reproduce

Firefox: https://www.webpagetest.org/result/230129_BiDc82_8V7/1/details/#waterfall_view_step1

Chrome: https://www.webpagetest.org/result/230129_BiDc61_8T7/1/details/#waterfall_view_step1

### Website version

6b63c7311a13a54703922bc619ddffc4e612aded

### What browsers are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### Other information

I can submit a PR if desired

**Comment by Koen1999** [comment]
@rinkp, if you can create a PR for this, I will happily approve it.

**Comment by rinkp** [comment]
I don't think preloading the favicon will have any additional benefit as the favicon will not be displayed in any current major browser while the webpage is loading;
I'm not sure whether there are downsides, I can't imagine it significantly slowing down any other requests that are needed
Removing the version tag in gewisicons causes the preload not to be used sadly
