### ISSUE TITLE
Change poll link text to something more descriptive

### ISSUE THREAD

**Issue by nielsly** [GEWIS/gewisweb#1611]
### What would you like?

Change "VIEW THE RESULTS"/"LAAT DE RESULTATEN ZIEN" under the poll on the main page to something like "VIEW DETAILS" or similar.

### Why is this needed?

Currently the poll in the sidebar on the main page has a "VIEW THE RESULTS"/"LAAT DE RESULTATEN ZIEN" link, which takes you to a page with the poll's results and comments, however the results are already shown if you are logged out, or have filled out the poll, possibly making the text confusing.

Changing the text to something more descriptive would improve UX.

**Comment by tomudding** [comment]
I don't see how it can be confusing, as you will be viewing the results when you click on it. However, we will change it to be more descriptive.
