### ISSUE TITLE
Upgrade to DoctrineModule v6

### ISSUE THREAD

**Issue by Koen1999** [GEWIS/gewisweb#1637]
### What would you like?

Upgrade to `doctrine/DoctrineModule` v6.
The most prominent change is the changes to the caching dependencies.
As a result of this upgrade, we can drop the dependency on the deprecated `doctrine/cache`

Please see:
https://github.com/doctrine/DoctrineModule/releases

**Comment by tomudding** [comment]
I am planning on upgrading all dependencies once ORM v2.15.2 is released which contains a fix that we have been waiting for (and was blocking all other dependency updates). This also applies to GEWISDB.

**Comment by tomudding** [comment]
> and was blocking all other dependency updates

Because it is incredibly frustrating to have to manually bump Composer versions and not have everything upgrade at the same time.

**Comment by tomudding** [comment]
- [ ] `doctrine/doctrine-orm-module` also needs support for `doctrine/doctrine-module`.

**Comment by Koen1999** [comment]
> * [ ]  `doctrine/doctrine-orm-module` also needs support for `doctrine/doctrine-module`.

Good spot, I have created an issue to keep track of this.
https://github.com/doctrine/DoctrineORMModule/issues/735

**Comment by tomudding** [comment]
The required patches for `doctrine/doctrine-orm-module` were just merged, I expect an update later today and will provide a PR with the updated dependency.
