### ISSUE TITLE
Adding number fields to activities is not possible

### ISSUE THREAD

**Issue by rinkp** [GEWIS/gewisweb#1676]
### Current behaviour

When editing an (unapproved) activity, it is not possible to add a numerical signupfield. Neither board members nor the creator can edit this

When first adding a text field and then changing the type, the following error is shown because the min and max fields are not shown and don't have a default value:
![image](https://github.com/GEWIS/gewisweb/assets/17340320/a3b1a171-acea-47c6-af7e-ad31d355b19f)

### Steps to reproduce

1. Create an activity as a regular user with a signuplist
2. Try to add a signup list field
3. A post is submitted to the same page and your field is gone without any feedback
4. Posting again will not create the field instead saving the activity as is

### Website version

715f02d06e9dcd8389cd4761efac55139baf463e

### Other information

First reported by Lucy

**Comment by tomudding** [comment]
This is a JavaScript issue from what I can see, the `select` requires an additional update before displaying the fields.

**Comment by tomudding** [comment]
Actual cause is that the `click` event is on the `<select>` and not the `<option>`s.
