### ISSUE TITLE
Improved i18n routing

### ISSUE THREAD

**Issue by tomudding** [GEWIS/gewisweb#1682]
### What would you like?

In GH-1370 the i18n aspects of the website were improved, including alternate `hreflang`s in the `<head></head>` for translations. Unfortunately, this negatively impacted search engine results due to the additional redirect. The functionality was disabled in bbfd63e2362ef3eb1f6ee16775b5cc87be17db4a to mitigate this.

Because we cannot go the route of the additional redirect, I suggest implementing a new router stack that is able to handle `https://gewis.nl/en/{actual route}` and `https://gewis.nl/nl/{actual route}`.

I still have to figure out how to make the old URLs work* but parsing the `/:lang/` part is relatively easily (as the route stack matcher will just have to change the `baseUrl` to include the `:lang/` part to have the normal route stack matching handle everything else).

This also includes the automatic detection of language and changing the URL accordingly.

**Comment by tomudding** [comment]
On top of this we can also use the `TranslatorAwareTreeRouteStack` to translate the traditional routes (after the new route stack as proposed above). This would mean that you have, for example, `gewis.nl/en/activity` and `gewis.nl/nl/activiteit`.

**Comment by tomudding** [comment]
I don't know which language Google prefers when indexing. Maybe to make sure that Google does not get mad, if your preferred language is English you can stay on `/` (and not be redirect to `/en/`) and if Dutch you automatically go to `/nl/`. `/en/` will of course work too.

**Comment by rinkp** [comment]
> I don't know which language Google prefers when indexing. Maybe to make sure that Google does not get mad, if your preferred language is English you can stay on `/` (and not be redirect to `/en/`) and if Dutch you automatically go to `/nl/`. `/en/` will of course work too.

I think having `/en/` and `/nl`/ would be a good idea. Currently the default is English so we can keep the homepage like that.

**Comment by rinkp** [comment]
When we do this, we may consider having both an English and a Dutch title for custom pages, but on the other hand I don't think the router supports that, so then we would need an if-else everywhere we generate URLs (such as navigation)

**Comment by tomudding** [comment]
> When we do this, we may consider having both an English and a Dutch **_title_** for custom pages, but on the other hand I don't think the router supports that, so then we would need an if-else everywhere we generate URLs (such as navigation)

Title or route? For routing of custom pages we can just add an additional set of "routes". Based on the `:lang` from `gewis.nl/:lang/:category[/:sub_category][/:name][/]` we can determine whether we need to look up the Dutch route or the English route.

Then, for example, `/en/custom/page` and `/nl/speciale/pagina` both work but `/en/speciale/pagina` and `/nl/custom/page` won't work.

> I think we already will get a problem with people linking to their Dutch page from their English page and vice versa.

Maybe I didn't quite think this idea through after all. For custom pages we can add an explicit link to the page "Show in English"/"Toon in het Nederlands".

**Comment by tomudding** [comment]
While the implementation part of this is proving to be reasonably easy (I am having some issues with the homepage) we need to be very careful when deploying this. It will become a very easy way to destroy our search results if not done properly (especially for all "old" URLs).

**Comment by rinkp** [comment]
> ... we need to be very careful when deploying this. It will become a very easy way to destroy our search results if not done properly (especially for all "old" URLs).

We definitely need redirects for the old URLs to /en/$1 (if not for anything else than for existing inbound hyperlinks)

**Comment by tomudding** [comment]
> > When we do this, we may consider having both an English and a Dutch **_title_** for custom pages, but on the other hand I don't think the router supports that, so then we would need an if-else everywhere we generate URLs (such as navigation)
> 
> Title or route? For routing of custom pages we can just add an additional set of "routes". Based on the `:lang` from `gewis.nl/:lang/:category[/:sub_category][/:name][/]` we can determine whether we need to look up the Dutch route or the English route.
> 
> Then, for example, `/en/custom/page` and `/nl/speciale/pagina` both work but `/en/speciale/pagina` and `/nl/custom/page` won't work.

This requires some additional changes for the `hreflang` stuff to work.

**Comment by tomudding** [comment]
> > ... we need to be very careful when deploying this. It will become a very easy way to destroy our search results if not done properly (especially for all "old" URLs).
> 
> We definitely need redirects for the old URLs to /en/$1 (if not for anything else than for existing inbound hyperlinks)

The current implementation does not change the behaviour of these pages, they just work like they used to work. They are either in Dutch or in English. However, I do want to add automatic redirects, similar to what Microsoft does. This will work for anything that cannot be translated but will result in 404's for things with translations:

> Then, for example, `/en/custom/page` and `/nl/speciale/pagina` both work but `/en/speciale/pagina` and `/nl/custom/page` won't work.
