### ISSUE TITLE
Activity: allow sign-up list option to be visibly by organiser only

### ISSUE THREAD

**Issue by rinkp** [GEWIS/gewisweb#1683]
### What would you like?

We discussed this a while when we were working on the privacy statement and I remember thinking about organiser-only options on sign-up lists. In that way, things such as dietary preferences and contact information can be communicated with the organizer securely without using an external platform. 

![example of how it could look](https://github.com/GEWIS/gewisweb/assets/17340320/ec0567e1-60bd-4974-a417-55ec573a12ad)

**Comment by tomudding** [comment]
Do you think we should create a separate field for this (the problem then becomes enumerating through all options) or just a checkbox?

**Comment by rinkp** [comment]
> Do you think we should create a separate field for this (the problem then becomes enumerating through all options) or just a checkbox?

Checkbox I think; I assume it can work with all option types
