### ISSUE TITLE
Organ cover photo crop aspect ratio is not the same as display aspect ratio.

### ISSUE THREAD

**Issue by Kevinjil** [GEWIS/gewisweb#1713]
### Current behaviour

The image is cropped to a 16:5 aspect ratio, while it is displayed with a 16:4 aspect ratio. This causes some unexpected heads to be cut of in the final result and several attempts to upload a "working" image.

### Desired behaviour

The cropped preview and aspect ratio are the same as displayed on the website.

### Steps to reproduce

- Upload image
- Preview crop result
- Image gets approved
- End result on website differs from preview

### Website version

5aaece8

### What operating are you seeing the problem on?

Other

### What browsers are you seeing the problem on?

Other

### Other information

See [_frontpage.scss](https://github.com/GEWIS/gewisweb/blob/5aaece8ea3be290b19a8b95369a720dd9c938d2d/public/scss/modules/_frontpage.scss#L7) and [edit.phtml](https://github.com/GEWIS/gewisweb/blob/5aaece8ea3be290b19a8b95369a720dd9c938d2d/module/Decision/view/decision/organ-admin/edit.phtml#L247).

**Comment by tomudding** [comment]
This is tracked via GH-1052 and ABC-2211-148.
