### ISSUE TITLE
Allow member search on m-number

### ISSUE THREAD

**Issue by BHenkemans** [GEWIS/gewisweb#1734]
### What would you like?

I would like to be able to fill in the m-account number in the  "Find a Member" module.

### Why is this needed?

Because in some one-off scenarious (for instance a Google Form) people sign up with their m-account email and then it would be convenient to easily look up who filled in the form

**Comment by tomudding** [comment]
If you already have the number there is no need to search..., you can just use the link: https://gewis.nl/member/{lidnr}.

**Comment by tomudding** [comment]
Bartjan agrees, however, if someone else wants this feature they are of course allowed to open a PR for it.
