### ISSUE TITLE
ATHENA Function ordering on their fraternity page is wrong

### ISSUE THREAD

**Issue by Yaneriaf** [GEWIS/gewisweb#1791]
### Current behaviour

The current ordering is 
Chair
Treasurer
Vice-Chair
Secretary

### Desired behaviour

Preferably, this ordering would be
Chair
Secretary
Treasurer
Vice-Chair

This would be in line with the other fraternities (and organs for that matter) (except I.V.V, but that is due to people having double functions.)

### Steps to reproduce

Open the website
Open the fraternity page of ATHENA
It is there.

### Website version

v4.1

### What operating are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Firefox

### Other information

Would be a nice first issue :)

**Comment by tomudding** [comment]
Sorting of the functions happens here:

https://github.com/GEWIS/gewisweb/blob/d2091d798d33fd11cac2aa9f10b59669b0b1c223/module/Decision/src/Service/Organ.php#L410-L421

It only tries to put the chair first (or people with more functions).
