### ISSUE TITLE
Redirect back to page after login

### ISSUE THREAD

**Issue by JeroenvdV** [GEWIS/gewisweb#1831]
### What would you like?

When clicking a specific link while logged out, logging in brings me back to the website homepage. I now have to go back and click the deep link again. Example: https://gewis.nl/en/decision/ALV/118

### Why is this needed?

It saves clicks

**Comment by tomudding** [comment]
Thank you for this request. This already works if you use the "Login" link that is on the actual page:
![image](https://github.com/GEWIS/gewisweb/assets/4983571/c25eca35-eb78-4a9a-b537-f5564fa21677)

Using the login button in the menu does indeed not have the same effect.

**Comment by tomudding** [comment]
Thanks again for bringing this to our attention. The changes are expected to be live in about 30 minutes.
