### ISSUE TITLE
Job postings: attachment URL always visible

### ISSUE THREAD

**Issue by rinkp** [GEWIS/gewisweb#1869]
### Current behaviour

https://github.com/GEWIS/gewisweb/blob/cd42dec69674f36a2798c33f547d25aeab0e438f/module/Company/view/company/company/jobs.phtml#L130

This statement seems to be always true resulting in the attachment URL to always be shown

Other layouts use a different check:
https://github.com/GEWIS/gewisweb/blob/cd42dec69674f36a2798c33f547d25aeab0e438f/module/Company/view/company/admin-approval/job-approval.phtml#L202

### Desired behaviour

The attachment hyperlink is only shown when there is an attachment that can be downloaded

### Steps to reproduce

1. Open any of the job listings of https://gewis.nl/en/career/company/infiniot
2. The attachment button is visible
3. Clicking the attachment button results in a 403 for `/data`

### Website version

https://github.com/GEWIS/gewisweb/commit/cd42dec

### What operating are you seeing the problem on?

Linux, Other

### What browsers are you seeing the problem on?

Firefox

**Comment by tomudding** [comment]
Caused by GH-1821.
