### ISSUE TITLE
Poll date input Y-m-d confusion

### ISSUE THREAD

**Issue by rinkp** [GEWIS/gewisweb#1888]
### Current behaviour

Currently, the poll approval form indicates it is a YYYY-mm-dd date field. 
Since a date picker is used, the final format depends on the localisation the browser users. When using Dutch in MS Edge, the browser prefers dd-mm-YYYY

https://github.com/GEWIS/gewisweb/blob/e3d122d45852ee825644f9d502011dfc038fe41e/module/Frontpage/src/Form/PollApproval.php#L25-L26

### Desired behaviour

Less confusion, since most broeders support the date field now, I think the hint can be removed

```diff
-                    'label' => $translator->translate('Expiration date for the poll (YYYY-MM-DD)'),
+                    'label' => $translator->translate('Expiration date for the poll'),
                    'format' => 'Y-m-d',
```

### Steps to reproduce

1. Create a poll
2. Click approve poll 
3. Observe end date input

### Website version

v4.3.2 (https://github.com/GEWIS/gewisweb/commit/404d9b79cc2b338678a4b8d4523c8b6d7b9f2cbe)

### What operating are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Firefox, Microsoft Edge

### Other information

Originally reported by the board. Good first issue, neither a bug nor a feature

**Comment by tomudding** [comment]
@rinkp do you want to create the PR yourself?
