### ISSUE TITLE
Provide an API

### ISSUE THREAD

**Issue by jszanto** [GEWIS/gewisweb#216]

**Comment by kokx** [comment]
What kind of API? What kind of interfaces should it expose?

**Comment by jszanto** [comment]
Just a basic RESTful API, it would serve two puposes:

1. Internal use: Usage by the website itself through AJAX requests. For example to facilitate a fancy photo viewer or to allow instant searching.

2. External use: There are various other systems which currently pull data from the website. Such as information and poster screens. 

For (2) there should at least be endpoints to obtain a list of upcoming activities and recent photos. The endpoints required for (1) partially exist already, however it may be desirable to group them together with an API route.

**Comment by kokx** [comment]
Is this really needed for version 1.0?

Also, this issue is pretty broad, maybe this should be split up in several parts?

**Comment by jszanto** [comment]
Closing this since it was replaced by less broad issues.
