### ISSUE TITLE
AV machtigingen

### ISSUE THREAD

**Issue by jszanto** [GEWIS/gewisweb#217]

**Comment by kokx** [comment]
Dit valt in principe onder de scope van het bestuur. En kan dus waarschijnlijk beter onder `~secr` neergezet worden.

**Comment by jszanto** [comment]
Het is momenteel onderdeel van de website en past ook goed in het leden gedeelte. In ieder geval mag deze functionaliteit niet zomaar verdwijnen

**Comment by jszanto** [comment]
Fixed by #579
