### ISSUE TITLE
Let the file storage service return files in a memory-friendly way

### ISSUE THREAD

**Issue by kokx** [GEWIS/gewisweb#221]
Currently, the `Zend\Http\Response\Stream` class returns the file by simply concatenating the contents of fhe file into a string. And then outputting that string. Thus, the data in the file is completely loaded into PHP's memory.

In PHP, it would be better to use one of the built-in `readfile()` or `fpassthru()` functions. Because these will directly forward the stream onto `stdout`. Without reading it into memory (and especially not introducing possible string concatenations with `O(n)` complexity.

Possibly it may also be wise to file an issue for this upstream.

**Comment by kokx** [comment]
After some testing, I'm not entirely certain if `readfile()` and `fpassthru()` are the best functions here. When testing with a large file (larger than PHP's memory limit), both these functions would simply give a memory limit. However, the following code does it's job nicely:

```php
$fp = fopen($file, 'rb');
while (!feof($fp)) {
    echo fread($fp, 1024);
}
fclose($fp);
```

Note that buffering is disabled here of course.

**Comment by jszanto** [comment]
Since `Zend\Http\Response\Stream` actually already uses `fpassthru()` and I have not noticed any performance issues at all I'm closing this for now.
