### ISSUE TITLE
Link dinner options to activities

### ISSUE THREAD

**Issue by jszanto** [GEWIS/gewisweb#235]

**Comment by stefanmajoor** [comment]
This is pretty much part of #126. 

If there is something more, that is not part of #126, reopen and provide some additional details about what should be done

**Comment by jszanto** [comment]
This is not the same as #126, since not all people signing up to an activity want dinner and not all people whom want dinner want to join the activity.

**Comment by stefanmajoor** [comment]
Ah, I see, you want more of an eating activity that is directly linked to a normal activity. Is that something that is really necessary for the first version? It is possible to have two seperate activities, just like is done with the current site.

**Comment by jszanto** [comment]
I'm not sure why this has been added to the version 1 milestone @kokx? This indeed is just a nice feature to have in the future, but not essential.

**Comment by kokx** [comment]
I didn't completely get that either. And indeed, it is more of a nice-to-have. I have removed the v1 milestone.

**Comment by Koen1999** [comment]
May be part of the activity overhaul

**Comment by mstruijs** [comment]
@Koen1999 The proposed decoupling of activities and signup lists in the overhaul will indeed make this easier: a dinner option list is then just another signup list associated to the activity. However, if this issue has some sort of priority, it can also be done before the overhaul.

**Comment by Koen1999** [comment]
@mstruijs , there is no priority, so it's probably more convenient to complete the overhaul first.
