### ISSUE TITLE
Photo: Automatically generate covers for albums

### ISSUE THREAD

**Issue by kokx** [GEWIS/gewisweb#249]
At the moment, covers aren't generated automatically for albums. You manually have to click on the button to generate an album cover.

**Comment by jszanto** [comment]
The question is, when should this be done? Doing it after the album is created is not so useful, since then the cover would just be blank. Doing it after every single photo upload is rather inefficient.

**Comment by kokx** [comment]
I propose to do the following when a photo is uploaded:

- If there is no cover, immediately generate one.
- If there is a cover, have a 10% (or some other number) chance to generate a new cover.
