### ISSUE TITLE
Photo: Generating covers for albums with less than 4 images fails

### ISSUE THREAD

**Issue by kokx** [GEWIS/gewisweb#250]
We should have some kind of gracefull fallback for this

**Comment by jszanto** [comment]
When there are less then 4 images, it first searches sub-albums, then falls back to 2 images and then falls back to 1 image. At least, this is the way it was implemented and it /should/ work.

**Comment by kokx** [comment]
For some reason, it does work now, while it didn't work yesterday. So right now I can't reproduce it.

**Comment by kokx** [comment]
Since I cannot reproduce this issue anymore, I'm closing this.
