### ISSUE TITLE
Allow users to upload summaries

### ISSUE THREAD

**Issue by kokx** [GEWIS/gewisweb#272]
Allow users (GEWIS members) to upload summaries, with an approval system for the education officer.

**Comment by Koen1999** [comment]
This could work by allowing users to submit summaries on the website. The educational officer then receives an email to review the summary. It will not be displayed on the website until it is approved

**Comment by Koen1999** [comment]
I think this is slightly too much work compared to what we get from it. Sending a mail to co@gewis.nl shouldn't be a big issue for members.
