### ISSUE TITLE
Photo: Moving albums works non-intuitively

### ISSUE THREAD

**Issue by kokx** [GEWIS/gewisweb#280]
Possibly allow the user to immediately nest an album when creating it.

**Comment by jszanto** [comment]
Albums can be nested when creating them. If you select an existing album and click the create album button while that album is open, then it will become a child album.

**Comment by kokx** [comment]
Actually, that doesn't work. If you do that, you get rerouted to the main photo admin page. Where you then can click on the create album page, which of course doesn't nest.

**Comment by jszanto** [comment]
Well that's a bug then, for which a seperate issue should be made.
