### ISSUE TITLE
Activity: CSRF vulnerability on activity signoff

### ISSUE THREAD

**Issue by gafderks** [GEWIS/gewisweb#375]
You do not need to use the form to signoff for an activity. It should not be possible to signoff by only requesting an url like `/gewisweb/public/activity/signoff/9`.

**Comment by mstruijs** [comment]
I'm not exactly sure what you mean. Since the signoff is done via HTTP GET, this indeed means that it is vulnerable to the most trivial CSRF attacks, so it should probably be done via POST instead.

**Comment by gafderks** [comment]
A POST should be used indeed, but you should also include a CSRF token.
