### ISSUE TITLE
Activity: Redirect activity/signup and activity/signoff to activity/view

### ISSUE THREAD

**Issue by mstruijs** [GEWIS/gewisweb#393]
Since the user should not visit the signup and signoff routes, but only POST to them, remaining on these routes gives unneeded error messages when reloading the page (e.g. when logging in or out). Note that the messages are printed in the signup and signoff routes, so this should be changed as well.

**Comment by mstruijs** [comment]
Displaying the messages in view.phtml and removing signoff.phtml and signup.phtml would work, but I'm not sure if that is the place where we want those messages. @stefanmajoor, @gafderks, what do you think?

**Comment by gafderks** [comment]
I think there's no problem in putting those messages into view.phtml.

**Comment by stefanmajoor** [comment]
The routes should become POST only (also because of CSRF vulnerabilities). And after a POST request, the user always needs to be redirected to a get page. I think that view.phtml is the correct place to show the messages
