### ISSUE TITLE
Polls: comment dates

### ISSUE THREAD

**Issue by jszanto** [GEWIS/gewisweb#398]

**Comment by kokx** [comment]
I don't think that comments need titles. But a date is something that needs to be added indeed.

**Comment by jszanto** [comment]
The old website has titles for comments

**Comment by kokx** [comment]
That doesn't mean that we need them.

**Comment by jszanto** [comment]
It currently seems to be a feature which is used. We could just add it as an optional field?

**Comment by kokx** [comment]
It is 'used' because the field is there. In most other places, simple comments like these don't have titles. Thus, unless people start asking for it (which I suspect they won't), I'm not going to add it.
