### ISSUE TITLE
Company: Hosting images from 'company in the spotlight' article locally

### ISSUE THREAD

**Issue by wsinnema** [GEWIS/gewisweb#403]
At the moment, there is no way to directly upload images for usage in the articles. However, at the moment, it is possible to upload unpublished banners, and use the url of the images of those banners in the articles

**Comment by jszanto** [comment]
You can possibly use the existing page_admin/upload url route to upload the image or you could at least use the existing service function.

**Comment by tomudding** [comment]
The company spotlight will be removed as part of the company module overhaul. The replacement is a selection of pre-existing jobs, hence we do no longer need an upload mechanism for the pictures.
