### ISSUE TITLE
Design: navigation menu for education module does not look good at some sizes

### ISSUE THREAD

**Issue by wsinnema** [GEWIS/gewisweb#407]
In the screenshot below, having the items two by two or three by one (with the last one centered) would look better.
![2015-12-30-234055_1920x1080_scrot](https://cloud.githubusercontent.com/assets/798647/12058705/e84209fa-af4e-11e5-8a09-f0075ebf0fd4.png)

**Comment by gafderks** [comment]
This is not a bug. This is because you have an old version of the CSS files. You can fix this by running `grunt css`.

**Comment by wsinnema** [comment]
The updated version looks a bit better, but still not optimal. I think a grid would look much better, or at least more space efficient when it fits.
![2015-12-31-234643_1920x1080_scrot](https://cloud.githubusercontent.com/assets/798647/12068902/ef9fad7c-b018-11e5-902f-107d9e647040.png)

**Comment by gafderks** [comment]
Also when the items are displayed vertically, on mouse-over, grey squares appear on the left of the page.

**Comment by gafderks** [comment]
@armandduijn As you have worked on this page, can you maybe investigate this further?

**Comment by kokx** [comment]
It seems that this isn't that much of an issue. I think we have more important things to do for 1.0.
