### ISSUE TITLE
Fatal error: cannot redeclare moduleIsActive()

### ISSUE THREAD

**Issue by stefanmajoor** [GEWIS/gewisweb#437]
Rebased my branch with master, and suddenly got this error:

```
Fatal error: Cannot redeclare moduleIsActive() (previously declared in /var/www/html/gewisweb2/module/Application/view/layout/layout.phtml:2) in /var/www/html/gewisweb2/module/Application/view/layout/layout.phtml on line 2
````

Tried to update to some older revision (one I knew that was good), but got the same issue still, then did a clean clone of the gewisweb repository, and the error was still there, which makes me suspect that this is either a caching problem, or a dependency problem

Is there somebody else with the same problem?

**Comment by wsinnema** [comment]
I got the same error after updating php to version 7, but I've not been able to solve it yet. When using php5 from xampp, everything still works.

**Comment by jszanto** [comment]
This is usually caused when something inside the layout throws an exception. Because in the case of an exception the layout gets loaded again which results in the double declared function.

**Comment by kokx** [comment]
First make sure your database schema is up to date. It seems that this error occurs when it tries to load the error page from the layout (because it reloads the layout).

Still, this needs fixing, such that it won't happen at all. Thus, I will do that.
