### ISSUE TITLE
Missing or incorrect URLs in navigation

### ISSUE THREAD

**Issue by jszanto** [GEWIS/gewisweb#440]
These include but are not limited to:
- [ ] Books
- [ ] exams
- [ ] members
- [ ] SuSOS
- [ ] Activity creation in main nav

**Comment by kokx** [comment]
The members URL actually is in the nagivation when you are logged in. Next to your own name.

**Comment by jszanto** [comment]
There indeed are two members buttons after you login, but neither of them has a working URL.
