### ISSUE TITLE
Activity: Unapproved activities can be subscribed to

### ISSUE THREAD

**Issue by jszanto** [GEWIS/gewisweb#455]

**Comment by stefanmajoor** [comment]
Is this really a security vulnerability? What is exactly the big problem with this happening?

**Comment by jszanto** [comment]
It perhaps isn't really a security vulnerability, but it is a bug which should be fixed. It gives people a false impression that an activity has been approved while actually it hasn't. Furthermore some activities may never be approved at all.

**Comment by kokx** [comment]
Are unapproved activities visible in the interface? If not, I'd say this doesn't really matter.

**Comment by jszanto** [comment]
After creating an activity, the creator is redirected to a page displaying that activity. This gives a false impression that the activity has been approved. I'd rather see a short message noting that the activity has been created succesfully and will be reviewed.

**Comment by kokx** [comment]
That would be exactly what we need.

**Comment by jszanto** [comment]
Fixed in #596 I believe
