### ISSUE TITLE
Display photos of the week by year

### ISSUE THREAD

**Issue by jszanto** [GEWIS/gewisweb#511]

**Comment by jszanto** [comment]
Or provide some other way to see from which year a photo was on the photo of the week page.

**Comment by gafderks** [comment]
I plan on implementing an album of photos of the week with subalbums per year (same approach as for albums of a member, #782), does this offer the wanted functionality?

**Comment by Kevinjil** [comment]
@gafderks I think that would be even better as just displaying them by year.

**Comment by Koen1999** [comment]
This is still something that we can implement

**Comment by tomudding** [comment]
This was implemented with #1424.
