### ISSUE TITLE
Show a recent photo of a member whom has a birthday

### ISSUE THREAD

**Issue by jszanto** [GEWIS/gewisweb#514]
Currently the oldest photo is shown

**Comment by armandduijn** [comment]
@Mesoptier Is this bug being tackled in issue #470?

**Comment by jszanto** [comment]
This issue is just a matter of adding an `orderBy` to a query, it isn't design related.

**Comment by armandduijn** [comment]
Hmm. Isn't this already done? The query orders by tag ID descending.

[Line 93 in gewisweb/module/Photo/src/Photo/Mapper/Tag.php](https://github.com/GEWIS/gewisweb/blob/a582d2f499d3d910c04d899c581615198a72d1dc/module/Photo/src/Photo/Mapper/Tag.php#L93)

**Comment by jszanto** [comment]
It should probably order by the photo datetime instead, since the tag id doesn't tell us anything about when the photo was taken.
