### ISSUE TITLE
Add thumbnailing for organ images

### ISSUE THREAD

**Issue by kokx** [GEWIS/gewisweb#525]
Currently, organ images are used as uploaded. Which usually is too large. They should be automatically thumbnailed so they load quickly on the committees and fraternity pages.

**Comment by BorBorBor** [comment]
Additionally they should be clickable, so you can view them in full. Currently they are weirdly cropped: 

![schermafbeelding 2016-02-10 om 15 26 48](https://cloud.githubusercontent.com/assets/6693412/12949928/d84de1c2-d00a-11e5-9ae4-757c7c29cdf8.png)
