### ISSUE TITLE
Translate actvity icons

### ISSUE THREAD

**Issue by mstruijs** [GEWIS/gewisweb#526]
Translate the month abbreviations in the activity icons. 
Related to #492.

**Comment by armandduijn** [comment]
Fixed when #623 is merged

**Comment by armandduijn** [comment]
Should be fixed in #623 so this issue can be closed.

**Comment by armandduijn** [comment]
Whoops. The badges were removed from the homepage so this problem wasn't tackled in #623. Re-opening...

**Comment by jszanto** [comment]
This is only an issue in May and October right?

**Comment by Kevinjil** [comment]
Probably also for March

**Comment by armandduijn** [comment]
I guess. This issue can be resolved by just replacing `DateTime::format` to `strtotime()` and setting the locale correctly.

**Comment by jszanto** [comment]
Perhaps we should just ditch the date icons and redesign the activity pages.

**Comment by jszanto** [comment]
If we implement #421 we could do some nice stuff with the design

**Comment by armandduijn** [comment]
Agree. So this is a won't fix?

**Comment by mstruijs** [comment]
@armandduijn  Eh, let's just close it as 'outdated'.
