### ISSUE TITLE
Committee names with non-alnum chars don't have a working committee page

### ISSUE THREAD

**Issue by kokx** [GEWIS/gewisweb#537]
See https://gewis.nl/association/committee/EJC16-%CF%80

Probably because of this line: https://github.com/GEWIS/gewisweb/blob/3ed84b1fe9adec87d66cb72bb6c6b3a2d8784dba/module/Frontpage/config/module.config.php#L52

**Comment by stefanmajoor** [comment]
The same issue appears at the fraternity page.

The url should be able anything except a / i guess to fix this. (i.e. '[^/]')
