### ISSUE TITLE
Admin menu does not display items

### ISSUE THREAD

**Issue by gafderks** [GEWIS/gewisweb#549]
The first time (today) I opened the admin page (gewis.nl/admin), there was an Organs option. After some browsing on the website, 5 minutes later, the Organs option is gone.

**Comment by jszanto** [comment]
Did you log out in the meanwhile or resize your browser window to <992px?

**Comment by gafderks** [comment]
I did not log out. I don't recall whether I resized the window, but that _should_ not matter since the 'Organs' option is the only option that shows up for me on the admin page.

**Comment by jszanto** [comment]
I'm unable to reproduce this issue. However no matter how many items are in the admin menu, it always disappears completely if the window size is <992px. (that's another bug which needs to be fixed).

**Comment by jszanto** [comment]
Since this can't be reproduced and the issue with small screen sizes was fixed I am closing this.
