### ISSUE TITLE
Also display company in the spotlight on the main company page

### ISSUE THREAD

**Issue by jszanto** [GEWIS/gewisweb#561]

**Comment by wsinnema** [comment]
Needs discussion

**Comment by jszanto** [comment]
Has been discussed. The best option is to display the current contents of the spotlight page inside a box on the main company page. This box should be collapsible so it can't take up the whole page at once. Also if no spotlight article is provided then the description of the company should be displayed.

**Comment by jszanto** [comment]
Fixed in some commit
