### ISSUE TITLE
Photo: Zoekfunctie voor foto's en albums

### ISSUE THREAD

**Issue by jszanto** [GEWIS/gewisweb#57]

**Comment by kokx** [comment]
What exactly do we want to search for here? People in photo's?

**Comment by jszanto** [comment]
People in photos, activities, cats, etc. Also would be nice to have it you could search for combinations of people/activities.

**Comment by Koen1999** [comment]
Finding people, possibly in combination with activities seems reasonable.
Finding cats however.....

**Comment by jszanto** [comment]
Finding cats seems quite doable https://github.com/tensorflow/models/tree/master/research/object_detection

However they don't appear that often in GEWIS photos
