### ISSUE TITLE
Photo: on photo deletion don't delete file if it is attached to another entity

### ISSUE THREAD

**Issue by jszanto** [GEWIS/gewisweb#583]
If two identical albums are created and then one of them is deleted, files go missing.

**Comment by kokx** [comment]
Maybe just don't delete files at all? It's not like we need the storage space or something like that.

**Comment by jszanto** [comment]
Since the files are publicly accessible there may be some rare cases in which it is desirable to fully delete them, but for now not deleting them probably is good enough.

**Comment by kokx** [comment]
I think we can handle those cases manually.
