### ISSUE TITLE
Photo: Importeren van geüploade foto's d.m.v. (S)FTP

### ISSUE THREAD

**Issue by jszanto** [GEWIS/gewisweb#59]

**Comment by kokx** [comment]
In veel gevallen zal de website deze foto's niet kunnen verwijderen. Waarschijnlijk zullen deze dan onder GEFLITST staan. Waar je de rechten niet hebt om ze te verwijderen. Daarnaast zou ik zeggen dat het niet altijd gewenst is om ze te verwijderen.

**Comment by jszanto** [comment]
Het is makkelijk om zo bij te houden welke foto's al geïmporteerd zijn, maar dit doen we dan wel op een andere manier.
