### ISSUE TITLE
Photo: Autofocus on tagging field

### ISSUE THREAD

**Issue by gafderks** [GEWIS/gewisweb#600]
For tagging a large number of people in a large number of photos it is handy when you do not constantly need to select the field for focus. We can add the autofocus-attribute to the field.

Old:
`<input type="text" class="form-control" name="tagSearch" id="tagSearch" 
autocomplete="off">`

New:
`<input type="text" class="form-control" name="tagSearch" id="tagSearch" 
autocomplete="off" autofocus />`

Suggested by Willem Mouwen

**Comment by gafderks** [comment]
I suggest not implementing this as it makes the page automatically scroll down to the input field. On mobile devices (where the field is displayed below the picture) this is very disturbing.

**Comment by jszanto** [comment]
Maybe we can make it re-focus after creating a tag instead of auto focusing it always?
