### ISSUE TITLE
Migrate to PHP 8.0

### ISSUE THREAD

**Issue by armandduijn** [GEWIS/gewisweb#603]
We need to migrate! A few reasons why we should invest our limited time and motivation in a likely painful and, lets be honest, a likely unsuccesfull endeavor:
- It has the spaceship operator
- the rest you can read on [this page](https://www.quora.com/What-benefits-does-PHP-7-bring-in-terms-of-real-time-functionalities)

This biggest improvement is obviously that it's blazing fast!

![qxq0jq](https://cloud.githubusercontent.com/assets/706385/16299472/cb7079da-393a-11e6-906e-e84fe64d9ed8.jpg)

So, when are we going to make a migration plan?

**Comment by kokx** [comment]
Though I'm definitely 100% and more for this awesomazing plan. The web committee doesn't make this happen.

This is all CBC. And they probably don't want to support it, because it's not in Debian's repositories.

**Comment by armandduijn** [comment]
I come with good news! After running [php7cc](https://github.com/sstalle/php7cc) on our source code, only one issue was found. So we are nearly good to go. Only the servers need a upgrade...


```
> Line 6: Name "resource" that is reserved for future use (does not cause an error in PHP 7) used as a use statement alias
```

**Comment by Koen1999** [comment]
According to https://www.php.net/supported-versions.php, our current PHP version has reached the end of it's lifetime. There will be no security updates as well and that might be an issue.

**Comment by Koen1999** [comment]
As discussed during the meeting, we will first wait for the CBC to provide a server that support PHP 7.

**Comment by armandduijn** [comment]
Nevermind PHP 7. Let's go for latest and greatest: [PHP 8](https://www.php.net/releases/8.0/en.php) 🎉.

**Comment by armandduijn** [comment]
We're getting to close the 5 year anniversary of this issue. Any update on the migration?

**Comment by kokx** [comment]
We're getting there. With the new server environment, we will be moving to a container based setup for production Soon™. Which means that we control the PHP version ourselves.

**Comment by Koen1999** [comment]
> 
> 
> We're getting close to the 5 year anniversary of this issue. Any update on the migration?

Actually, the Docker PR that's currently open upgrades to PHP 7.1. Still not the newest, but this was the only upgrade that could be done without big changes due to dependencies. It's an amazing first step though.

**Comment by Koen1999** [comment]
This is (mostly) resolved by https://github.com/GEWIS/gewisweb/pull/1119.

**Comment by tomudding** [comment]
Good news! I am reopening this issue to hopefully close it again with our newest PR (which is the upgrade* to PHP 8.0.4).

*: Really only an upgrade, any new features (such as native attributes) are not used, _yet._
