### ISSUE TITLE
Create admin dashboard

### ISSUE THREAD

**Issue by armandduijn** [GEWIS/gewisweb#621]
The index page of the admin page (/admin) is an untapped gold mine 😱! We could use it to display useful information such as the amount of unapproved activities, submitted polls, and other tasks.

![download](https://cloud.githubusercontent.com/assets/706385/17935077/5c9e052a-6a1a-11e6-8656-d9b0aab6902c.png)

**Comment by armandduijn** [comment]
@jszanto Could you check with the GEWIS board what they want on the dashboard? Which pieces of information do they want to have an overview of? We already discussed a list of open tasks (e.g. approve poll, approve activity) but are there more?

**Comment by jszanto** [comment]
We could also use some of this space to display changelogs of website updates, so users will learn about new features sooner.

**Comment by armandduijn** [comment]
How would the changelog be stored? Using a markdown file? We could use the same library that processes markdown in activity descriptions.

**Comment by jszanto** [comment]
Perhaps some entries in the database would be handier? Then we can update them more easily.

**Comment by gafderks** [comment]
If we really want to do it nicely, we use the GitHub API.

**Comment by kokx** [comment]
I think a changelog in a Markdown file would be better. So we can update it while committing a new release.

**Comment by armandduijn** [comment]
It now has a changelog so I consider this issue fixed.
