### ISSUE TITLE
Datepicker not displayed correctly

### ISSUE THREAD

**Issue by armandduijn** [GEWIS/gewisweb#632]
In the new option calendar the "Add option" form is a little awkward. I noticed that in Safari the datepicker is cut off the screen. The form is also quite small. It doesn't work well for long activity names.

<img width="221" alt="schermafbeelding 2016-09-09 om 16 47 16" src="https://cloud.githubusercontent.com/assets/706385/18391142/48c38ce2-76ad-11e6-84d8-880b86489e09.png">

**Comment by jszanto** [comment]
This is because you haven't recompiled your css

**Comment by armandduijn** [comment]
I was on test.gewis.nl...

**Comment by jszanto** [comment]
Then it is because the css wasn't recompiled on test.gewis.nl

**Comment by armandduijn** [comment]
Oke. Issue resolved I guess.

**Comment by jszanto** [comment]
Just closed it a second time to be sure
