### ISSUE TITLE
Show the GPS location of a photo in the details

### ISSUE THREAD

**Issue by gafderks** [GEWIS/gewisweb#634]
This is especially interesting for weekends like the GELIFT weekend.

**Comment by jszanto** [comment]
How would we obtain the location? I think the location will only be available on the very few photos which are taken with a phone.

**Comment by gafderks** [comment]
That is true. We can only display it if it is included in the EXIF data.

**Comment by kokx** [comment]
@jszanto Actually, a lot of the photo's might already contain GPS data. AFAIK, the GEFLITST camera has a GPS function.
