### ISSUE TITLE
Preferred language

### ISSUE THREAD

**Issue by jszanto** [GEWIS/gewisweb#636]
Allow logged in users to choose their preferred language so we can automatically set their language. This also is useful for emails.

**Comment by gafderks** [comment]
We can also detect the language of the client browser: https://github.com/basz/SlmLocale

**Comment by tomudding** [comment]
Since a few releases ago, users can set their preferred language through their browser's settings (`Accept-Language`). Therefore, I am closing this issue. If we want to implement actual user settings at some point (e.g., privacy settings) we can create a new issue for this.
