### ISSUE TITLE
Activity admin improvements

### ISSUE THREAD

**Issue by jszanto** [GEWIS/gewisweb#642]
Currently the activity admin is not so user friendly. I'll update this later with some ideas for improvements which I had. We also should make sure that this issue doesn't conflict with issue #594

**Comment by stefanmajoor** [comment]
Do you have some more information about this yet about what we really want?

**Comment by jszanto** [comment]
I had the following idea, obviously open for feedback and changes.

 For non-admins we could have the following view:
![screenshot from 2016-10-02 15-47-16](https://cloud.githubusercontent.com/assets/7968933/19021024/a58ec1f4-88b8-11e6-9ff5-da5405e8e865.png)

This will give you a quick overview of all activities created by you or the organs which you are part of. (Past and future activities) Clicking the edit button brings you to the page to submit a modification request and export brings you to the page to export the subscriptions. The approval status icons are the same ones which we have on the organ information page.

For admin users I had a very similar view in mind
![screenshot from 2016-10-02 15-54-30](https://cloud.githubusercontent.com/assets/7968933/19021052/04660a2a-88b9-11e6-87f6-edc560ffe7d3.png)

Here clicking an activity brings you to the admin page for the activity which allows you to approve and reject it (same way as it works currently). Activities are split in 3 categories to keep some overview (for the user view they can be all in one list since there will be far less activities). The "awaiting approval" category contains all unapproved activities and all activities which have changes awaiting approval.

**Comment by stefanmajoor** [comment]
@jszanto I am planning on first creating the updated view for admin users, and then creating the my activies admin view from that. 

If I understand the second picture correctly, the updated and new activites have been merged?

**Comment by jszanto** [comment]
@stefanmajoor Yes they have been merged, since I think this would create a better overview.

**Comment by mstruijs** [comment]
@stefanmajoor Fixing issue #655 has led to essentially a solution for this issue, so I will be fixing this as well.

**Comment by mstruijs** [comment]
Closed by #704 .

**Comment by mstruijs** [comment]
Closed by #704 .
