### ISSUE TITLE
Prevent excessive poll deletion

### ISSUE THREAD

**Issue by jszanto** [GEWIS/gewisweb#643]
Currently polls are deleted too often which destroys the poll history. This issue may be resolved by some better UX or by introducing soft deletes.

**Comment by kokx** [comment]
I think delete should not be a valid option on polls at all. Marking them as 'unfit' or 'denied' might be better.

**Comment by jszanto** [comment]
I think there should be two options, one to soft delete/hide the poll completely and one to expire the poll such that it still shows up in the history.
