### ISSUE TITLE
Having to register for a lunchlezing twice.

### ISSUE THREAD

**Issue by mhverbakel** [GEWIS/gewisweb#664]
If you click "register" for a lunchlezing without being logged in, you get redirected to the login page. If you then log in, you are still not registered for the lunchlezing: you have to click register again. This is not intuitive, since you would expect that the login page redirecting back executes the requested action.

**Comment by gafderks** [comment]
I think this is not really an issue since the button does not look like an action button but is a link that brings you to the login page. Maybe the text on the link can be changed to "Om in te kunnen schrijven moet je eerst [inloggen](https://gewis.nl/user)" to clarify it a little more.
