### ISSUE TITLE
Exams button on Education page does not do anything

### ISSUE THREAD

**Issue by Staartvin** [GEWIS/gewisweb#670]
When navigating to the Education page, four buttons appear (and an exam searching method at the end of the page). The button 'Exams' does not do anything since that already exists below the buttons. . Hence, I propose to either move the exam searching method to another, separate page or to hide the current exam searching method until you click the Exams button.

**Comment by mstruijs** [comment]
Another option, which has been implemented in the latest release, is to keep both the button and the search bar, but give focus to and highlight the search bar when the button is clicked.

@gafderks: Does this modification resolve this issue?

**Comment by gafderks** [comment]
I think it is at least better than it was in the first place.

**Comment by armandduijn** [comment]
Is this issue resolved?

**Comment by mstruijs** [comment]
@armandduijn: I'll leave that up to you. IMO, the current functionality of the exam button and search option is fine and the suggestions by @Staartvin only serve to force the user to use more 'clicks' to get to a search field. So I see neither a problem, nor an improvement in this conversation.

**Comment by jszanto** [comment]
Fixed in #756
