### ISSUE TITLE
Use 301 Moved Permanently for gew.is

### ISSUE THREAD

**Issue by gafderks** [GEWIS/gewisweb#672]
Right now 302 Found is used. The 301 status is more suitable.

**Comment by mhverbakel** [comment]
:+1:

**Comment by jszanto** [comment]
Why would we use 301 for a temporary redirect?

**Comment by kokx** [comment]
Because it actually is a permanent redirect. So a 301 redirect is correct.

**Comment by jszanto** [comment]
Since it is no longer a redirect I am closing this for now.
