### ISSUE TITLE
Not all jobs are displayed for a company in the spotlight

### ISSUE THREAD

**Issue by gafderks** [GEWIS/gewisweb#673]
Rabobank currently (29-11-2016) has two jobs but the 'spotlight' on the company homepage only shows one.

Screenshots:
On https://gewis.nl/company 
![image](https://cloud.githubusercontent.com/assets/7315457/20730331/f971a9a8-b685-11e6-80d5-dbeddc3f0ebe.png)

On https://gewis.nl/company/rabobank
![image](https://cloud.githubusercontent.com/assets/7315457/20730346/0ba9c376-b686-11e6-8dfa-99ef5d00d284.png)

**Comment by Koen1999** [comment]
Does anyone know whether this bug is still present?

**Comment by tomudding** [comment]
This is no longer an issue, as this functionality (showing a list of jobs for the spotlight package) has been removed in preparation of the company module overhaul.
