### ISSUE TITLE
Old board members are still admin even while they no longer are a board member

### ISSUE THREAD

**Issue by jszanto** [GEWIS/gewisweb#674]
This is due to us checking the discharge date when determining the rights.

Using the AssociationYear class which @gafderks made we could easily check if someone is a board member in the current association year.

**Comment by Koen1999** [comment]
We should check whether this still is a bug and if so, fix this issue.

**Comment by jszanto** [comment]
I can confirm that this bug did not magically disappear.

**Comment by Koen1999** [comment]
The situation has improved since commit 960aea9eb547aed18b9645a9f6d91873a3140884
