### ISSUE TITLE
Company in the spotlight design doesn't work well at certain resolutions

### ISSUE THREAD

**Issue by jszanto** [GEWIS/gewisweb#675]
On some devices you will get a huge company logo on the page. It seems the responsive design doesn't work that well here.

**Comment by gafderks** [comment]
Can you give a more detailed description of what goes wrong?

**Comment by Koen1999** [comment]
@jszanto @armandduijn Is this an active issue or has it been resolved since?

**Comment by armandduijn** [comment]
I don't know the status of the issue and I haven't encountered this bug. Nobody has complained in the last two years so I think we can close it.
