### ISSUE TITLE
Member's page navigation is confusing

### ISSUE THREAD

**Issue by jszanto** [GEWIS/gewisweb#676]
Currently the member's page (https://gewis.nl/member) is just a pile of links which makes it difficult to find things you need.

**Comment by jszanto** [comment]
Perhaps we should add some categories?

![screenshot from 2016-12-02 23-24-21](https://cloud.githubusercontent.com/assets/7968933/20852540/901fa762-b8e6-11e6-9b29-ad2065c2815f.png)

**Comment by Staartvin** [comment]
I agree with adding categories. Otherwise it'll stay a bunch of random links.
