### ISSUE TITLE
Activity: improve activity list view.

### ISSUE THREAD

**Issue by mstruijs** [GEWIS/gewisweb#685]
Improve the view of the (public) activity list by rendering the Markdown of the description in the list (in addition to the single view) and display only the first X lines of the description.

**Comment by gafderks** [comment]
![image](https://cloud.githubusercontent.com/assets/7315457/21660281/0cbe4880-d2cf-11e6-89c4-ae1af3599850.png)

Is this to your liking? @Mesoptier @armandduijn @mstruijs

**Comment by Mesoptier** [comment]
Looks fine to me.
