### ISSUE TITLE
Make member photo's browseable like an album

### ISSUE THREAD

**Issue by kokx** [GEWIS/gewisweb#695]
When you view the photo's of a member, you should be able to go into an album of all the user's photos. Next and previous should work correctly here as well. If done correctly, this should fix #681 as well.

**Comment by jszanto** [comment]
Duplicate of #553

**Comment by kokx** [comment]
I don't agree that it's a complete duplicate of #553. Yes, the next and previous buttons are duplicate. However, I am also suggest to make it look like an album, with a complete album page and pagination and everything. So it kinda looks like:

![photos-user-album](https://cloud.githubusercontent.com/assets/138556/21693109/ede73546-d37f-11e6-99b6-a2d138cb1ea7.png)
