### ISSUE TITLE
EXIF orientation information is lost on thumbnail creation using Imagick

### ISSUE THREAD

**Issue by gafderks** [GEWIS/gewisweb#707]
Example: https://gewis.nl/photo/view/110299 and then click to download in full resolution.
Other example: https://gewis.nl/photo/view/110219

**Comment by gafderks** [comment]
This seems fixable by rotating the images before making thumbnails: http://php.net/manual/en/imagick.getimageorientation.php#111448

Or apply it just for the thumbnails: https://github.com/GEWIS/gewisweb/blob/master/module/Photo/src/Photo/Service/Admin.php#L92

**Comment by kokx** [comment]
Is this really an issue anyway? I don't think we really need the exif information in the non-full versions?

Also, this may be solved by moving to the new automatic thumbnail system.
