### ISSUE TITLE
Admin interface for activities does not look good on smaller screens.

### ISSUE THREAD

**Issue by Staartvin** [GEWIS/gewisweb#718]
While the overhaul of the admin interface for the activities is great, it is not responsive and looks horrible on mobile. 

A few examples provided below:

At MD resolution (992px):
![image](https://cloud.githubusercontent.com/assets/1338071/21782018/2910cabc-d6b2-11e6-98d8-07878cc797fe.png)

At SM resolution (768px):
![image](https://cloud.githubusercontent.com/assets/1338071/21782098/84751cf0-d6b2-11e6-983e-e904c1602eaf.png)

**Comment by gafderks** [comment]
I think this has very low priority as the admin interface for activities is probably very rarely used on mobile devices.

**Comment by tomudding** [comment]
I am closing this issue as I believe that #1260 (and #952) has improved this a lot.
