### ISSUE TITLE
Company pages are broken

### ISSUE THREAD

**Issue by gafderks** [GEWIS/gewisweb#719]
All pages for companies are currently broken: 

https://gewis.nl/company/nedap shows 
![image](https://cloud.githubusercontent.com/assets/7315457/21787125/b761ed68-d6c7-11e6-8b3c-6fa735374375.png)

Job pages are still OK: 
- https://gewis.nl/company/applied-micro-electronics-ame-bv/jobs
- https://gewis.nl/company/applied-micro-electronics-ame-bv/jobs/System-and-network-administrator-

**Comment by gafderks** [comment]
Seems to have been resolved.

**Comment by jszanto** [comment]
This was a php 5.4 compatibility issue, hotfixes have been applied.
