### ISSUE TITLE
Activity: Allow changing options in certain cases.

### ISSUE THREAD

**Issue by mstruijs** [GEWIS/gewisweb#728]
It is generally not possible to change options of activities, due to the problems that arise with already subscribed members. 

However, it is useful to be able to change/add/remove options when 1) the activity has not been approved and 2) no-one has been subscribed to the activity. 

Enable this functionality in the described case.

**Comment by Koen1999** [comment]
I don't believe such scenarios occur a lot or are generally worth putting in a lot of effort. We can probably close this instead.

**Comment by mstruijs** [comment]
It has happened a few times in the past that we rewrote the DB directly to resolve these scenarios. I agree that this does not have a high priority, but I don't see why we should close it. I'd say that anything that makes manual DB access unnecessary is at least 'nice to have'.

**Comment by Koen1999** [comment]
Agreed
