### ISSUE TITLE
Activity list has needless gaps in mobile view

### ISSUE THREAD

**Issue by mstruijs** [GEWIS/gewisweb#734]
On small screens, the additional data (dates, location, etc.) for activities is placed below the description instead of to the side. For activities with short descriptions, the space taken by the description is the same as the maximum possible space, so there is a noticeable gap between the activity and the data.

**Comment by jszanto** [comment]
I believe this was fixed https://github.com/GEWIS/gewisweb/pull/730

Just still is waiting to be released.

**Comment by mstruijs** [comment]
@jszanto Ah, indeed, it's already fixed.
