### ISSUE TITLE
Link from "members-page" to intro-app

### ISSUE THREAD

**Issue by marzman95** [GEWIS/gewisweb#735]
For the upcoming introductionweek, a nice feature would be to have a button on the page for members, to link to the app for the intro (REX, intro.gewis.nl). Since the app probably will work with SuSOS, being logged in would be nice.
It can also be nice, but not necessary, to have the button only appear for the members who are intro-parent or organization. This could be fetched from the REX-database.
The intro-committee and Jim will start setting up REX after the exam weeks.

**Comment by jszanto** [comment]
A button can be added, however automatically logging in is not possible since REX does not use the website API for logins.

**Comment by kokx** [comment]
Not relevant anymore.
