### ISSUE TITLE
Photo: Previous and next photo relation

### ISSUE THREAD

**Issue by jszanto** [GEWIS/gewisweb#74]
Een manier vinden en implementer om efficiënt voor elke foto te weten wat de volgende en vorige foto in het album is. Voor gebruik op de foto details weergave pagina.

**Comment by jszanto** [comment]
Ik bedacht me dat dit eigenlijk vrij triviaal is en dat een extra issue hiervoor overbodig is.

**Comment by nickygerritsen** [comment]
Bij de oude site ging dit eerst via de file modification time, maar dat werkt niet omdat dat niet overeen komt met wanneer de foto is gemaakt. Dat hebben we toen naar exif datum aangepast maar dat berekende we on the fly, wat voor problemen zorgt met de sortering, zeker als foto's geen exif hebben. Beter lijkt me de sortering bij inladen al te bepalen, dan voorkom je dat wel denk ik.

Groetjes,

Nicky

(verzonden vanaf m'n telefoon)

**Comment by kokx** [comment]
In dat geval, geeft zo'n issue dan een label zoals wontfix oid. Altijd als je een issue closed, geef een reden mee!

**Comment by jszanto** [comment]
Zal ik voortaan doen @kokx! Ik kan trouwens als collaberator geen labels, milestones of assignees toevoegen.

@nickygerritsen Ik had ook in gedachte om bij het importeren/toevoegen ervoor te zorgen dat de foto's in de goede volgorde of in ieder geval met een goede datum in de database te stoppen. Dat maakt het laden van de paginas ook sneller. Daarna is het vrij eenvoudig om de foto's in de juiste volgorde te retrieven. Sortering zou bij het ontbreken van exif data mogelijk ook kunnen afhangen van filenames. Aangezien de meeste camera's de foto's netjes in de juiste volgorde zetten aan de hand van nummers in de filenames.

**Comment by nickygerritsen** [comment]
Dat laatste gaat fout bij verschillende camera's, maar het is toch meer voor het geval er geen exif is en dat is over het algemeen wel :)

Groetjes,

Nicky

(verzonden vanaf m'n telefoon)
