### ISSUE TITLE
Lunch lectures page

### ISSUE THREAD

**Issue by wsinnema** [GEWIS/gewisweb#740]
A page with information for students and teachers about upcoming lunch lectures. Ask Levi for more information.

**Comment by jszanto** [comment]
Can this be done with a simple page added through the pages CMS which we currently already have?

**Comment by wsinnema** [comment]
I think so, but I think someone needs to talk to him about what he wants with it

**Comment by mstruijs** [comment]
After a quick discussion with Levi, we decided that the feature requested is:

* Create a page for career related activities, with essentially the same layout as /activity suggested route is activity/career
* Show exactly the activities with the 'career related' field marked on this page.
* Find a reasonable way to link to this page. A link from /activity is a suggestion.
