### ISSUE TITLE
Provide public XML-dump of all career activities

### ISSUE THREAD

**Issue by mstruijs** [GEWIS/gewisweb#746]
To automatically have career activities from `gewis.nl` imported into the 'myFuture' website, `gewis.nl` should expose an XML-dump of all career activities on some route. The 'myFuture' website will check for updates in the XML daily at 3.00 AM (No, the document doesn't list the timezone).

The precise XML-formatting, rules and further details are specified in a document mailed by ceb .

**Comment by kokx** [comment]
This doesn't really seem like a priority at the moment. This can be reopened if needed.
