### ISSUE TITLE
Number of vacancies on company overview page does not match actual number of vacancies

### ISSUE THREAD

**Issue by BorBorBor** [GEWIS/gewisweb#748]
E.g. currently TNO has 3 (says 38), Topicus has 3 (says 6).

**Comment by jszanto** [comment]
Duplicate of #657

**Comment by jszanto** [comment]
However this is a better description of the issue actually

**Comment by BorBorBor** [comment]
Ha, kind of explains why I wasn't able to find the other issue.

**Comment by jszanto** [comment]
Fixed in https://github.com/GEWIS/gewisweb/commit/8da2a2fb2322f5c1d4aa51737e335071d7019097
