### ISSUE TITLE
Merge two organ pages into one organ page.

### ISSUE THREAD

**Issue by Staartvin** [GEWIS/gewisweb#770]
There are two organ pages; [a detailed one](https://gewis.nl/association/committee/WC) and a page that only [shows the history of the members of the organ](https://gewis.nl/organ/show/75). 

Why not merge these two pages? Create a link that allows a user to go from the detailed organ page to the members history called 'view history of members of this organ'. Currently, the only way to go the history page is by going into 'Member' -> 'Organs' -> 'WC'.

**Comment by BorBorBor** [comment]
To add, an overview of 'former committees' might be nice to have. Currently the only way to find those is through URL hacking, while there are many epic examples that are nice to check out for members interested in the history of GEWIS:

https://gewis.nl/organ/show/9 (https://gewis.nl/organ/show/9)
https://gewis.nl/organ/show/20 (https://gewis.nl/organ/show/20)
November 2, 2017 1:22 PM, "Vincent Bolta" <notifications@github.com (mailto:%22Vincent%20Bolta%22%20<notifications@github.com>)> wrote:
	There are two organ pages; a detailed one (https://gewis.nl/association/committee/WC) and a page that only shows the history of the members of the organ (https://gewis.nl/organ/show/75). 

	Why not merge these two pages? Create a link that allows a user to go from the detailed organ page to the members history called 'view history of members of this organ'. Currently, the only way to go the history page is by going into 'Member' -> 'Organs' -> 'WC'.

**Comment by Koen1999** [comment]
I don't think that we should neccesarily merge them, as the detailed one contains a lot of information. We could provide a link to the detailed one on the committee page though
