### ISSUE TITLE
Show new and updated albums in a special row on top

### ISSUE THREAD

**Issue by Wezzz1993** [GEWIS/gewisweb#778]
To prevent photo albums not to be noticed if they are updated or put on the website with some delay, we would like to have a row of 4 albums at the top of the page which are the newest or most recently updated albums. This means there is a header New, with 4 albums under it, and then a header All with all pictures of that year. 

Or something like that

**Comment by Koen1999** [comment]
Is this something that we could perhaps implement as follows? You could add this badge to all albums younger than 7 days for example.

![afbeelding](https://user-images.githubusercontent.com/32361020/54275135-2af4cb00-458a-11e9-972a-18b97a2221b7.png)

`<div class="col-lg-3 col-md-4 col-xs-6 thumb">
<a class="thumbnail" href="/photo/album/1688">
<img class="img-responsive" alt="" src="https://imageog.flaticon.com/icons/png/512/3/3901.png?size=1200x630f&amp;pad=10,10,10,10&amp;ext=png&amp;bg=FFFFFFFF">
<div class="caption">Carnavalsborrel<span class="badge badge-primary">New</span></div></a>
</div>`

**Comment by Kevinjil** [comment]
Good idea, maybe an inline tag is also an option to consider:
![image](https://user-images.githubusercontent.com/32480819/54757353-514de280-4bea-11e9-8c3b-eed7fb8bd4d7.png)
