### ISSUE TITLE
Use Dutch date notation in agenda item badges

### ISSUE THREAD

**Issue by gafderks** [GEWIS/gewisweb#780]
Make the notation depend on the current language.

English (as it currently is): 
![image](https://user-images.githubusercontent.com/7315457/33799508-94515d28-dd2d-11e7-9b84-30bc7119004c.png)

When the website is switched to Dutch:
![image](https://user-images.githubusercontent.com/7315457/33799518-b153f08e-dd2d-11e7-8f44-aecf7fc720e2.png)

**Comment by jszanto** [comment]
Related: #526
