### ISSUE TITLE
Localization does not work for birthdays on homepage

### ISSUE THREAD

**Issue by BorBorBor** [GEWIS/gewisweb#783]
As of the new homepage (#623) the text announcing birthdays is written in English, also on the Dutch version of the homepage:

> XX wil be YY years old today!

Additionally this English string contains an error (`wil` should be `will`).

**Comment by gafderks** [comment]
While fixing this issue, you may also look into #787.

**Comment by jszanto** [comment]
This was fixed in 05836267a96741a6b831207b47d2a09877e6cf0a
