### ISSUE TITLE
Add timestamp to authorisation for GM

### ISSUE THREAD

**Issue by raketwissenschaftler** [GEWIS/gewisweb#791]
Currently, you can't see when somebody submitted their authorisation for a GM. A timestamp should be added

**Comment by husar** [comment]
Hello, I can solve this issue. Can you give me more information about this issue?

**Comment by Koen1999** [comment]
This is similar to #994 and can probably be solved best together.

**Comment by tomudding** [comment]
This was implemented in #1524.
