### ISSUE TITLE
Search through public dir from members panel

### ISSUE THREAD

**Issue by raketwissenschaftler** [GEWIS/gewisweb#797]
Allow logged in members to look through the public directory(containing logos and templates) from the GEWIS-website.

**Comment by raketwissenschaftler** [comment]
Upped the priority, because AVW 160 needs this feature quite urgently

**Comment by mstruijs** [comment]
Note that while this directory currently is on the same server as the webserver, this might change in the future. Therefore, it's a good idea to keep 'list directory' and 'download file' operations sufficiently abstract.

**Comment by raketwissenschaftler** [comment]
True. Although this also might be solved at the filesystem level with some hip mounting and symlinks if my Linux-knowledge is sufficient. However, it is good to keep this in mind.
