### ISSUE TITLE
Uploading an attachement to a job gives a HTTP 500

### ISSUE THREAD

**Issue by raketwissenschaftler** [GEWIS/gewisweb#798]
When uploading an attachement to a job, you get a HTTP error 500. The cause is unknown.

**Comment by jszanto** [comment]
stderr: PHP message: PHP Fatal error:  Call to undefined function Company\\Form\\Zend\\Validator\\File\\Extension() in module/Company/src/Company/Form/EditJob.php on line 152,

**Comment by jszanto** [comment]
Probably needs `new` and a `\` here https://github.com/GEWIS/gewisweb/blob/master/module/Company/src/Company/Form/EditJob.php#L152 and on line 155

**Comment by Kevinjil** [comment]
I tried it locally and the fix @jszanto suggets did solve the HTTP 500. However, the uploaded PDF is not saved to the server, and the link on the job page refers just to the data folder.
