### ISSUE TITLE
Language fallback for activities

### ISSUE THREAD

**Issue by jszanto** [GEWIS/gewisweb#801]
Provide some sort of easy fallback mechanism when one of the languages for an activity is missing instead of the hacky methods we currently have for this.

**Comment by raketwissenschaftler** [comment]
This should be implemented for job offers as well. Maybe implement it directly into the translate service?

**Comment by mstruijs** [comment]
Indeed, the current system is a mess that makes additions to the fields for activities an painful exercise (updates in about 3 different locations that are not at all obvious are required). This is the part that made me realize that the activity module needs a serious redesign.
