### ISSUE TITLE
Non-active members can't create activities

### ISSUE THREAD

**Issue by jszanto** [GEWIS/gewisweb#808]

**Comment by mstruijs** [comment]
Wasn't this by design? Anyway, this shouldn't be much more than a permission (maybe minor UI edit) fix.

**Comment by Kevinjil** [comment]
I spoke with the board about this issue, and the current behavior is the desired behavior.

**Comment by jszanto** [comment]
Can we at least hide the button?

**Comment by Kevinjil** [comment]
https://github.com/GEWIS/gewisweb/blob/354f42ea20799550b7c18bf6413127fda2c3ee46/module/Application/view/partial/main-nav.phtml#L180-L186
Right now the check for creating permission exists, but the call to `getEditableOrgans()` isn't allowed. Should we modify the rights to create activities?

**Comment by kokx** [comment]
Since, in the past, this was desired behavior, maybe we should not be too quick to knee-jerk and implement this? Unless there is a real usecase for this?

If non-active members do need to make an activity, they can still approach the board. Who can always make an activity.

**Comment by Koen1999** [comment]
I agree with @kokx, so does Sjoerd after thinking it over.
