### ISSUE TITLE
Categories are not linked to eachother

### ISSUE THREAD

**Issue by jszanto** [GEWIS/gewisweb#810]
When creating a job all categories show up twice in both languages. This is a strange UX since when creating a category is created for both languages

**Comment by tomudding** [comment]
Should we update the job creation form to be more like the activity creation form? In other words, selecting which languages to use and then have a single global (for both languages) category.

This change (with selecting the specific languages to be used) would also prevent empty languages from being created with the new label PR (see [#964](https://github.com/GEWIS/gewisweb/pull/964#issuecomment-654766640)).

**Comment by tomudding** [comment]
This was fixed when [feature/company-module-localisedtext](https://github.com/GEWIS/gewisweb/tree/feature/company-module-localisedtext) was merged as part of #1148.
