### ISSUE TITLE
Truncating of job descriptions messes up HTML code

### ISSUE THREAD

**Issue by jszanto** [GEWIS/gewisweb#811]
E.g. this description:

    <ul>
    <li>Item 1</li>
    <li>Item 2</li>
    <li>Item 3</li>
    </ul>

might get truncated to 

    <ul>
    <li>Item 1</li>
    <li>Item 

which messes up the layout of the rest of the page

**Comment by gafderks** [comment]
You may use the front-end reveal functionality that is also used in the activity module. This only hides descriptions on the screen and does not mess with the HTML.

**Comment by tomudding** [comment]
This is no longer an issue, see GH-1760 (though the actual editor still needs to be replaced via GH-1576).
