### ISSUE TITLE
Add disclaimer to course page

### ISSUE THREAD

**Issue by raketwissenschaftler** [GEWIS/gewisweb#818]
The CO requested that we add a disclaimer to the course pages. See the e-mail for the exact text.

**Comment by raketwissenschaftler** [comment]
Text that should be put on the website, on the Courses page: 
"[Disclaimer: De tentamens op de site van GEWIS zijn verstrekt door Education & Student Affairs van de faculteit Wiskunde en Informatica van de TU/e. Mocht er onbedoeld een tentamen online zijn gekomen die niet gepubliceerd had mogen worden, laat dit dan weten aan het bestuur van GEWIS via bestuur@gewis.nl, dan zal dit tentamen worden verwijderd van de website.
Het is niet toegestaan om de samenvattingen of tentamens op deze website zonder toestemming van de auteur te gebruiken voor commerciële doeleinden, dit is strafbaar.]"



"[Disclaimer: The exams on the website of GEWIS are provided by Education & Student Affairs of the department of Mathematics and Computer Science of the TU/e. If an exam has been put online without the intention of the author, please let the board of GEWIS know by sending an email to bestuur@gewis.nl, then this exam will be removed from the website.
Using the summaries or exams on this website for commercial goals without the permission of the author is illegal.]"

**Comment by Kevinjil** [comment]
Maybe change bestuur@gewis.nl to board@gewis.nl for the english version?

**Comment by gafderks** [comment]
Note that there is a grammatical error in the Dutch text: [...] Mocht er onbedoeld een tentamen online zijn gekomen ~~die~~ dat niet gepubliceerd had mogen worden [...]
