### ISSUE TITLE
Add text about removing or changing member info at member page

### ISSUE THREAD

**Issue by raketwissenschaftler** [GEWIS/gewisweb#824]
Currently, there is no clear way to indicate that you want to remove or change your info in the GEWIS database. By request of the board, it would be nice if a text such as "If you want any of this data changed or removed, please contact the secretary at secretary@gewis.nl" would be added in the position below.
![capture](https://user-images.githubusercontent.com/6400064/36899611-2e7e7f9c-1e20-11e8-84c4-ebe5de533b38.PNG)

**Comment by BorBorBor** [comment]
`serc@gewis.nl` should be `secr@gewis.nl`. Actually, maybe it's better to write `secretary@gewis.nl` in full so it's clear to (less active) members which person is meant.

**Comment by Koen1999** [comment]
Is @raketwissenschaftler working on this? It should be an easy fix. If not I can do this
