### ISSUE TITLE
Incorrect form validation on Choice field with one language disabled

### ISSUE THREAD

**Issue by Mesoptier** [GEWIS/gewisweb#844]
- Create an activity with Dutch disabled and English enabled.
- Add a Choice field with some options and try to submit the form.
- ???
- "The number of English options must equal the number of Dutch options"

![image](https://user-images.githubusercontent.com/322632/47623203-b5262080-db0e-11e8-815c-16ae56101bda.png)

**Comment by tomudding** [comment]
This is resolved in a771b34 as part of the activity overhaul. As long as no one else has any problems with this we will wait till the activity overhaul can be (partially) merged.
