### ISSUE TITLE
Activity: Textboxes are white but cannot select them.

### ISSUE THREAD

**Issue by stefanhoekstra** [GEWIS/gewisweb#851]
When creating an activity, I cannot select for example the "inschrijfdeadline" or "organiserend orgaan". I can work around this by selecting a different textbox and tabbing to these examples, to force them to be edited but this should not be necessary.

**Comment by Kevinjil** [comment]
What device and browser are you using?

**Comment by stefanhoekstra** [comment]
I used the gen 2015 TUE laptop, lenovo thinkpad W541, with windows 8.1 (yes I know its bad), on Chrome build newest-something

**Comment by Koen1999** [comment]
I wasn't able to reproduce this issue in Chrome. If you are still having this issue, or someone else, please reopen this issue.
