### ISSUE TITLE
Automatically delete old logs

### ISSUE THREAD

**Issue by jszanto** [GEWIS/gewisweb#854]
Currently error logs are retained for an infinite amount of time. This period should be reduced to two weeks.

**Comment by kokx** [comment]
Which error logs exactly?

**Comment by jszanto** [comment]
The exception logs generated by monolog

**Comment by Kevinjil** [comment]
Hmm weird, the log files should be rotating with at most 10 files. I'll look into this as I also implemented it.

**Comment by tomudding** [comment]
This has not been an issue for quite some time, so I am closing this.
