### ISSUE TITLE
Career Calendar

### ISSUE THREAD

**Issue by Kevinjil** [GEWIS/gewisweb#867]
Many companies organize events which are interesting for GEWIS members, such as in-house days and company cases. On the website, there is no clear overview of these activities. Therefore, a separate activity list called "Career Calendar" is desired as a tab of the Activities page.

Furthermore, it would be desired to be able to list all career activities a company has planned on the companies' profile page.

The implementation of this feature would be greatly simplified if it is implemented after completion of the overhaul suggested in the [Activity redesign](https://github.com/GEWIS/gewisweb/wiki/Activity-Redesign).

**Comment by wsinnema** [comment]
Is this already implemented at https://gewis.nl/activity/career?
