### ISSUE TITLE
Activiteiten: identify members as part of organ

### ISSUE THREAD

**Issue by choutha** [GEWIS/gewisweb#87]

**Comment by jszanto** [comment]
Ik veronderstel dat dit nog op geïntegreerd moet worden in de activiteiten module voordat dit opgelost is?

**Comment by kokx** [comment]
Nee, vanuit de activiteitenmodule moet dit ergens aangeroepen worden. Het is misleidend dat hier 'Activiteiten:' staat.

@choutha Als ik dit fout heb, reopen deze issue gewoon
