### ISSUE TITLE
Remove login wall activities page

### ISSUE THREAD

**Issue by Koen1999** [GEWIS/gewisweb#878]
https://gewis.nl/activity is currently begind a login wall, this has to be removed in order to allow for external participants.

**Comment by stefanmajoor** [comment]
Note that this is not a bug. This login wall (if I remember) correctly, was created for privacy reasons, as everybody otherwise could see who joined which activity through a simple google search.

A fix would be to only show the amount of subscriptions if a person is not logged in

**Comment by Koen1999** [comment]
> Note that this is not a bug. This login wall (if I remember) correctly, was created for privacy reasons, as everybody otherwise could see who joined which activity through a simple google search.
> 
> A fix would be to only show the amount of subscriptions if a person is not logged in

Yes, I am aware of that. Yet The activity overview is completely unreachable if you're not logged in.
