### ISSUE TITLE
Add social media buttons to footer

### ISSUE THREAD

**Issue by Koen1999** [GEWIS/gewisweb#889]
The following links should be added: 
- Facebook - https://www.facebook.com/svgewis/
- Instagram - https://www.instagram.com/svgewis/?hl=nl
- LinkedIn - https://www.linkedin.com/company/study-association-gewis/

PS. It's a request from the board

**Comment by tomudding** [comment]
I'd like to point out that the Facebook "f" Logo was updated by Facebook as part of their FB5 plan at the start of May. The logo you (@Koen1999) added is the old version. The new logo is available through https://en.facebookbrand.com/assets/f-logo/.

**Comment by Koen1999** [comment]
I have created a new issue for this, will be resolved at some point
