### ISSUE TITLE
HTML bestanden in vacature attachment

### ISSUE THREAD

**Issue by wsinnema** [GEWIS/gewisweb#913]
>  Ik ben nu pas een paar weekjes begonnen als CEB'er, en heb gisteren ook voor het eerst gebruik mogen maken van de vacature pagina. Deze werkt erg fijn! Ik loop momenteel wel tegen 1 klein dingetje aan. Bij elke vacature is er de optie om een "attachment" in te voegen. Op de vacature zelf staat deze achter een tekst "toon vacature". Ik merk dat niet alle bedrijven nog pdf versies van hun vacatures meesturen, en het zelf maken hiervan voor mij is erg veel werk. Wat voor mij een hele fijne optie zou zijn is als ik ook html bestanden in kan voegen bij de "attachment", dan kan ik direct doorlinken naar de pagina op hun website waar de vacature staat :). Ik weet niet of dit veel werk is, maar mochten jullie binnenkort tijd hebben om hier naar te kijken dan heel graag! 

The board wants HTML files as attachment for jobs on the career page, but it's not clear whether they actually want to include a link. Personally, I don't want to add the ability to include a link (destination is not under our control, and can change at any time). The same hold for an HTML file that is not self contained and loads external resources. This means that there are two options:
1. Allow to add a self contained HTML file. (This doesn't seem useful for the board, and then we need to educate every board on how to recognize whether it's self-contained)
2. Add functionality to add an HTML file, and then it's dynamically converted to PDF on upload.

I think the second option is the only good option, but I'm not sure how feasible it is (HTML is not easy to render correctly), and whether it is worth the development time.

**Comment by Koen1999** [comment]
I think that instead of adding an HTML file, we could just include a link to the job page of the actual company. It allows for more flexibility and is a lot easier to implement.

**Comment by Koen1999** [comment]
This may be related, from an email sent by Susan on 20 September.

`Another function that is a bit confusing in my opinion on this page is the option within a vacancy where I add a file as an attachment. When I leave this attachment open it still appears on the website as 'view job' but forwards to nothing, leading viewers to an empty page. If it is possible to either leave this 'view job' option out if there is no attachment, or there is an option to 'turn it off' for a specific vacancy that would be very useful. The attachment thing is however not urgent in any way, but it would be nice in the future. `
