### ISSUE TITLE
Change subject of GEFLITST request email

### ISSUE THREAD

**Issue by Koen1999** [GEWIS/gewisweb#919]
The new subject should be: ``<abbreviation of committee/fraternity> <name of activity>``

Refer to the email from GEFLITST of September 6.

**Comment by Yoronex** [comment]
I think the email said <abbreviation of committee/fraternity> <name activity>

**Comment by Koen1999** [comment]
> 
> 
> I think the email said <abbreviation of committee/fraternity>

Some part of the naming was detected as code in my description. I fixed that now.

For further reference (in Dutch):
![afbeelding](https://user-images.githubusercontent.com/32361020/64521983-4fdbb800-d2f9-11e9-977a-c2d29b51d922.png)

**Comment by Koen1999** [comment]
@armandduijn A small remark on your current commit is that activities aren't always organized by an organ. So perhaps a case distinction on whether organ is null would work.
If there is no organ related to the activity, which is rare, we can just leave the information out I think

**Comment by armandduijn** [comment]
Does a `NULL` organ mean that it's a member initative? If that's the case I can hard-code some text like 'member initiative' so that GEFLITST knows what's up.

**Comment by Koen1999** [comment]
> 
> 
> Does a `NULL` organ mean that it's a member initative? If that's the case I can hard-code some text like 'member initiative' so that GEFLITST knows what's up. Alternatively, we could also use the user's name (e.g. "Armand: GELIFT 2050")

Yes, it indeed implies it's a member initiative. Your solution also sounds good.
