### ISSUE TITLE
Vacancy without attachment still shows 'view job'

### ISSUE THREAD

**Issue by Koen1999** [GEWIS/gewisweb#927]
Another function that is a bit confusing in my opinion on this page is the option within a vacancy where I add a file as an attachment. When I leave this attachment open it still appears on the website as 'view job' but forwards to nothing, leading viewers to an empty page. If it is possible to either leave this 'view job' option out if there is no attachment, or there is an option to 'turn it off' for a specific vacancy that would be very useful. The attachment thing is however not urgent in any way, but it would be nice in the future. 

From an email, sent by Susan on 20 September

**Comment by riverxside** [comment]
Hi, can you add me to the project ? I 'd like to solve this issue.

**Comment by Koen1999** [comment]
> 
> 
> Hi, can you add me to the project ? I 'd like to solve this issue.

Hey, good to hear you would like to help.
Anyone can fork the repository, make changes and then create a pull request. If you do so, we will review the code and deploy the changes.
If you would like to become a member of the Web Committee, you can send an email to web[at]gewis.nl
