### ISSUE TITLE
Overlap by long names

### ISSUE THREAD

**Issue by LeonVreling** [GEWIS/gewisweb#930]
There is an overlap, because FESTIVITEIT is too long. This makes sure that it doesn't fit in the grid layout

![Overlap in committee page](https://user-images.githubusercontent.com/49942406/65882582-9622b500-e395-11e9-9450-ce08e83339b4.png)

**Comment by tomudding** [comment]
Something similar to #819 should probably be implemented to fix this.

**Comment by LeonVreling** [comment]
Also the icons should be fixed, so that they fit in the boxes and are not sometimes below each other and sometimes next to each other
![WhatsApp Image 2019-10-09 at 10 42 31](https://user-images.githubusercontent.com/49942406/66465733-ae738d80-ea81-11e9-9244-90715d4311ba.jpeg)

**Comment by LeonVreling** [comment]
Also on pc, not just mobile

![image](https://user-images.githubusercontent.com/49942406/66465806-dcf16880-ea81-11e9-99c3-637f45de3f95.png)

**Comment by tomudding** [comment]
I propose two (CSS) solutions for this;
1) We have the overflow be filled with an ellipsis. However, this results only in one row of text being shown for all names. For the longer names this results in possibly only 2 words being fully shown. Hovering over a name should display the whole name.
2) We clamp the overflow for 2 (or 3) rows of text. This way a larger portion of the name is shown. However, this is not compatible with all browsers.

Regarding the icons I cannot see an easy fix.

**Comment by Koen1999** [comment]
Which browsers don't support option 2? I am not aware of any.

**Comment by tomudding** [comment]
@Koen1999 I suppose that IE is not used a lot any more. So it will not be a problem as [almost all recent versions of modern browsers](https://caniuse.com/#feat=mdn-css_properties_-webkit-line-clamp) support `-webkit-line-clamp`.

The second option is the preferred solution as it appears that the box containing the name is always of fixed size.

**Comment by Koen1999** [comment]
Given that even Microsoft does not recommend using IE anymore, support is
not an issue if you ask me.

Op do 24 okt. 2019 14:53 schreef Tom Udding <notifications@github.com>:
