### ISSUE TITLE
Metadata icon not visible in Chrome

### ISSUE THREAD

**Issue by armandduijn** [GEWIS/gewisweb#933]
The metadata icon (ⓘ) in the topbar of the new photo viewer is not visible in Chrome v77. It does show-up in Safari on macOS and iOS, though.

<img width="720" alt="Schermafbeelding 2019-10-04 om 13 07 12" src="https://user-images.githubusercontent.com/706385/66203363-7ac2ed00-e6a8-11e9-9eb3-a0336a077eed.png">

**Comment by jszanto** [comment]
I'm unable to reproduce this, is it perhaps caused by a chrome extension which you are using?

**Comment by armandduijn** [comment]
Indeed, you're correct. I narrowed it down to AdBlock. So it's not our fault, but a issue nonetheless. I'm guessing that a lot of our users have this extension installed.

Probably AdBlock is triggered by the word "share" in the class name.

**Comment by armandduijn** [comment]
Confirmed

<img width="1037" alt="Schermafbeelding 2019-10-18 om 14 14 25" src="https://user-images.githubusercontent.com/706385/67093502-1fb5ed80-f1b2-11e9-8993-f16002a9616d.png">
