### ISSUE TITLE
Photos are not sorted in chronological order

### ISSUE THREAD

**Issue by jszanto** [GEWIS/gewisweb#936]
In the new photo viewer

**Comment by husar** [comment]
Hello, I can solve this issue. Can you give me more information about this issue?

**Comment by LeonVreling** [comment]
The pictures don't appear in the same order in the old and new photo viewer.
Example:
Old photo viewer first page
![image](https://user-images.githubusercontent.com/49942406/66465920-11652480-ea82-11e9-8374-eaedb146185a.png)
New photo viewer first page
![image](https://user-images.githubusercontent.com/49942406/66465954-22ae3100-ea82-11e9-91de-0fbbfb4e8092.png)

**Comment by husar** [comment]
Ok.... There is probably some database right?..... Can you give me access to database and access to fotogallery?

**Comment by tomudding** [comment]
This was added in f9d9c74, which was after the original merge of that branch:
https://github.com/GEWIS/gewisweb/blob/f9d9c74b1515c5f7a3647dbab3dabc2489bbd6f5/module/Photo/src/Photo/Model/Album.php#L72-L76

_I added this comment to track progress._

**Comment by jszanto** [comment]
@tomudding doesn’t that mean this issue is resolved now?

**Comment by tomudding** [comment]
@jszanto The change has never been merged into master, I have created #1010 to do this.
