### ISSUE TITLE
Change icons on website

### ISSUE THREAD

**Issue by Gijsdeman** [GEWIS/gewisweb#943]
Kind request by the committee Stijl, change the icons on the website to the FontAwesome version such that it matches better with the corporate design.

**Comment by kokx** [comment]
I would argue that this is not an easy fix. Adding different icons and replacing them everywhere is quite a bit of work. Especially since they are in a different format than the FontAwesome versions.

**Comment by kokx** [comment]
Also, I think we should wait until the styleguide is actually finalized before doing implementing design things.

**Comment by GEWISstijl** [comment]
Hi,
We are currently working on converting all icons to a FontAwesome icon. 
We'll create a pull request where we change all the icons when we are done.

With stylish regards,
Stijl

**Comment by GEWISstijl** [comment]
Please see pull request #968 

Feel free to contact us if you have any questions.

With stylish regards,
Stijl
