### ISSUE TITLE
Make filling in dates for options easier

### ISSUE THREAD

**Issue by Koen1999** [GEWIS/gewisweb#945]
![afbeelding](https://user-images.githubusercontent.com/32361020/67479933-65196580-f65f-11e9-8ed4-65ee44962721.png)

When filling in the start date, it is known that the end date is after or on the start date.
To make this process easier, we can automatically set the end date to the start date once it has been filled in. Often these two dates are the same.

This was a request that came up during the CM.

**Comment by kokx** [comment]
Another option: we set the end date to the start date, but at 23:00

**Comment by Koen1999** [comment]
> 
> 
> Another option: we set the end date to the start date, but at 23:00

It's a date field. The time will not appear there, so there's no point in specifying a time.
