### ISSUE TITLE
Uploading summaries is not working

### ISSUE THREAD

**Issue by Koen1999** [GEWIS/gewisweb#947]
When uploading summaries, the website says no summaries were uploaded.
This probably also holds for uploading exams.

There have been no recent changes to the Education module, so it's a bit curious...

**Comment by tomudding** [comment]
@Koen1999 do you know which steps were taken during the upload process? Uploading summaries works fine locally.

**Comment by Koen1999** [comment]
I tried it myself as well, it is reproducable on the server. I can say that the documents upload was completed and that the error also occurs when not navigated to through history.

**Comment by Koen1999** [comment]
This was a file permission error on the server and is now resolved.
