### ISSUE TITLE
Replace adres in footer by link to contact page

### ISSUE THREAD

**Issue by jszanto** [GEWIS/gewisweb#971]
This prevents confusion about the address since there are 3 addresses and the footer only contains 2

**Comment by tomudding** [comment]
Do we have an idea of what it should look like (design-wise)? For example, do we want an extra line of text under the copyright notice or just add an extra item to the existing contact list?

**Comment by Koen1999** [comment]
> 
> 
> Do we have an idea of what it should look like (design-wise)? For example, do we want an extra line of text under the copyright notice or just add an extra item to the existing contact list?

Perhaps something like this? (but with a glyphicon)
![afbeelding](https://user-images.githubusercontent.com/32361020/72643253-8e9c1180-396e-11ea-960c-dc240bbe36c9.png)

Included html for reference:
```


<div class="row">
  <div class="col-sm-2 col-md-1">
    <img src="/img/gewis-footer.svg">
  </div>
  <div class="col-sm-7">
    <h3>Infima</h3>
    <p>
      (het gaat over Bor en Jim)
      Pieter: "Ik vraag me af wanneer jullie een blijde gebeurtenis aan gaan kondigen?"
      Bor: "Niet, weet je hoe veel geld ik dan aan Ylona moet betalen?"
      <script>
        var container = $('div.container');
        
      </script>                            
    </p>
    <p>© 2013
      - 2020 door de WebCommissie van GEWIS. Alle rechten voorbehouden.
    </p>
  </div>
  <div class="col-sm-3">
    <a href="vereniging/contact">Adres</a><br>
    <i class="glyphicon glyphicon-earphone"></i> <a href="tel:+31402472815">+31 (0)40 247 2815</a><br>
    <i class="glyphicon glyphicon-envelope"></i> <a href="mailto:bestuur@gewis.nl">bestuur@gewis.nl</a><br>
    <img src="/img/linkedin.ico" class="glyphicon" width="15" height="15"> <a href="https://www.linkedin.com/company/study-association-gewis/">LinkedIn</a><br>
    <img src="/img/facebook.ico" class="glyphicon" width="15" height="15"> <a href="https://www.facebook.com/svgewis/">Facebook</a><br>
    <img src="/img/instagram.ico" class="glyphicon" width="15" height="15"> <a href="https://www.instagram.com/svgewis/">Instagram</a>
  </div>
</div>
```

**Comment by Koen1999** [comment]
And it's like this on mobile then:
![afbeelding](https://user-images.githubusercontent.com/32361020/72643442-f9e5e380-396e-11ea-9951-6b6800f18d77.png)

**Comment by tomudding** [comment]
That is exactly what I meant with my second option. And it looks good! However, you might want to check what it does on "medium" screens, as I can imagine that the text can jump.

As for the icon, it depends on if you want to wait for #968 or not (I suggest waiting as I think it is "almost" ready to be used) to implement it.

**Comment by Koen1999** [comment]
I think we can wait for that PR

Op vr 17 jan. 2020 21:33 schreef Tom Udding <notifications@github.com>:

**Comment by jszanto** [comment]
I would rather name it "contact" instead of "address", since it should link to the contact page which has more than only the address.

**Comment by Koen1999** [comment]
I agree on that remark.

Op za 18 jan. 2020 13:58 schreef jszanto <notifications@github.com>:
