### ISSUE TITLE
Adding corporate identity button on member page

### ISSUE THREAD

**Issue by GEWISstijl** [GEWIS/gewisweb#975]
Adding a link on the [/member](https://www.gewis.nl/member) page to [/corporateidentity](https://www.gewis.nl/corporateidentity) as approved by the board.

As soon as #968 has been approved and merged, we'll provide you with a pull request using a beautiful FontAwesome icon

Can't add labels, but I think #quickfix and #frontend are appropriate

**Comment by Gijsdeman** [comment]
Duplicate of #944
