### ISSUE TITLE
Visiting a photo page in which an ex-member is tagged results in an exception

### ISSUE THREAD

**Issue by Koen1999** [GEWIS/gewisweb#991]
We should either find a way to automatically remove those tags or catch this exception somehow

**Comment by tomudding** [comment]
With the introduction of the new dynamic tag loading only the tags (and voted status) will fail to load, which greatly improves the UX. We still need to find a proper solution, but at least photos now stay accessible.

**Comment by tomudding** [comment]
This is no longer an issue with the introduction of the dynamic tag loading in #1391. If we hadn't used native SQL the error would have prevented tags from loading, however, now the query only returns valid values.
