### ISSUE TITLE
Show subscription date and time in admin overview

### ISSUE THREAD

**Issue by Koen1999** [GEWIS/gewisweb#994]
We could add an automatic field to the ActivitySignup model. After that we only need to display it on the appropriate admin page.

Request from Romy (Board)

**Comment by mstruijs** [comment]
The natural place to display this is the participants list. (`../admin/activity/<id>/participants`) This list is visible to both site admins and organizers of that activity. Do we want the organizers to view this data, or only admins?

Could you expand on what this data is going to be used for? If it's something simple like checking whether people subscribe close to the deadline or many people within a short timeframe, highlighting values that are interesting is easy to do and probably worthwhile. If they want to do more complicated analysis or visualization, the data should be in an easily exportable format.

Speaking of exportable formats, I don't think it would make sense to put this data on the pdf export of the participants list, unless that happens to be important for its usage.

**Comment by Koen1999** [comment]
I would say both could view them. But if it's only the admins that would be fine too.
I'm not sure of the use. I think it's for checking eligibility for activities with a limited capacity. They have been coming up with more complex policies

**Comment by mstruijs** [comment]
Hmm, if this is not very urgent I think it's better to first get a clearer idea of how they want to use the data.

**Comment by Koen1999** [comment]
This is similar to #791 and can probably be solved best together.
