### ISSUE TITLE
frontpage/poll/vote causes an exception

### ISSUE THREAD

**Issue by Koen1999** [GEWIS/gewisweb#996]
```
[2020-04-29 01:29:45] gewisweb.ERROR: exception 'Zend\View\Exception\RuntimeException' with message 'Zend\View\Renderer\PhpRenderer::render: Unable to render template "frontpage/poll/vote"; resolver could not resolve to a file' in /var/www/gewisweb/vendor/zendframework/zendframework/library/Zend/View/Renderer/PhpRenderer.php:493
```

See log files for complete stack trace

**Comment by tomudding** [comment]
`activity/activity/external-signup` has the same problem, but less frequent (it is not the homepage). I also noticed that the cause (as listed in the strack trace) also breaks `application_service_legacy`.

I think we should (at least) temporarily remove the offending script to reduce the size of the logs.

**Comment by Koen1999** [comment]
I would agree to employ a temporary fix to be able to see other potential
errors if it's feasible to deploy.

Op do 28 mei 2020 11:05 schreef Tom Udding <notifications@github.com>:

**Comment by tomudding** [comment]
I have taken another look in an attempt to fix this, to no avail. The templates which cannot be rendered do not exist, nor have they ever existed (according to the Git log). It feels very similar to the proxy issues we had in #995.

**Comment by Koen1999** [comment]
Mayby it's also worth noting that these exceptions do not appear in the logs of test.gewis.nl for some reason. Probably different deployment method
