### ISSUE TITLE
Contact page contents

### ISSUE THREAD

**Issue by rinkp** [GEWIS/gewisweb#999]
This is a low priority issue, front-end

On the English variant of the [contact page](https://www.gewis.nl/vereniging/contact), there are some things that I think could be improved slightly. Some things are less important than others, but if you are updating the page, you might as well update the others.

- The line height for the packaging address is more than for the other addresses 
![image](https://user-images.githubusercontent.com/17340320/82697735-c3480e80-9c69-11ea-851d-e81308d9e8e0.png)
- "Er is ook een routebeschrijving beschikbaar." is translated with "A route description is also available.". I'd suggest changing this into "Travel directions are also available"
- The hyperlink to aforementioned travel directions points to the dead page [/vereniging/route](https://www.gewis.nl/vereniging/route). Instead, it should refer to [/vereniging/contact/route](https://www.gewis.nl/vereniging/contact/route). Both Dutch and English have this.
- On the english page the email address for the board is listed as "bestuur@". The board already has the more international-friendly "board@". 
- "Commissioner External Relations" is mentioned twice. We usually translate this function with "External Affairs Officer"
- Other contact information lists "ABN-Amro:". Perhaps it is nice to update this line to "Bank account: NL22ABNA0528195913 (ABN Amro Bank, BIC: ABNANL2A). Similarly for Dutch
- "Hieronder kunt u als onze contact informatie vinden." --> "Hieronder kunt u **al** onze contact informatie vinden."
- "Study association GEWIS can be reached using several methods." --> "Study **Association** GEWIS can be reached **in** several **ways**." (capital letter is used later as well)
- The Dutch page mentions "De beheerder van de inhoud van elke pagina staat rechtsonder de pagina vermeld.", but I doubt that is still the case.

**Comment by rinkp** [comment]
@WoutervanHoof, as requested

**Comment by tomudding** [comment]
Thank you for reporting this. I will change it later today and get back to you to verify that I have made the correct changes.

**Comment by tomudding** [comment]
I have made the changes you requested. Please note that these pages are maintained by the board, if you find mistakes in the future, please send an e-mail to the board to get them to fix it.

---

> The hyperlink to aforementioned travel directions points to the dead page /vereniging/route. Instead, it should refer to /vereniging/contact/route. Both Dutch and English have this.
As far as I can tell the hyperlink is correct, thus I have not changed it.

**Comment by rinkp** [comment]
Ah, that's great.

The fact that they are maintained by the board explains that I wasn't able to find them in this repository.

The hyperlink has as target "route". This'll work if your current page is [/vereniging/contact/](https://gewis.nl/vereniging/contact/). However, it will not work if your current page is [/vereniging/contact](https://www.gewis.nl/vereniging/contact). The latter page is the page you enter by default when clicking the link in the footer. Going via "Association" -> Contact will leed you to the first indeed, where the hyperlink does work.
Then it'll go to the "route" page in the same directory you're in, resulting in the non-existent [/vereniging/route](https://gewis.nl/vereniging/route).

Maybe you could consider always redirecting [/vereniging/contact](https://www.gewis.nl/vereniging/contact) to [/vereniging/contact/](https://gewis.nl/vereniging/contact/) (and updating the footer to prevent an unneccessary 301's then), but I'd do that consistently across all pages, so [/education](https://www.gewis.nl/education) should then also redirect to [/education/](https://www.gewis.nl/education/)
The other way around is also possible of course. Either way, it requires extensive testing for all relative hyperlinks that exist.

**Comment by tomudding** [comment]
I see why I was not getting the wrong page. I have changed the links and I will probably change the link in the footer to include the slash, but it should work either way now.
